// Code generated by langlang codegen, DO NOT EDIT.
// Source: ../../../grammars/sku_record.peg

package binary

import (
	"encoding/binary"
	"fmt"
)

var _ = binary.LittleEndian
var _ = fmt.Errorf

type SkuRecord struct {
	Genre        PrefixedString
	ObjectId     PrefixedString
	TypeId       PrefixedString
	Tags         PrefixedStringList
	TagsImplicit PrefixedStringList
	BlobDigest   PrefixedString
	Description  PrefixedString
}

func DecodeSkuRecord(data []byte) (SkuRecord, int, error) {
	var out SkuRecord
	off := 0
	{
		val, n, err := DecodePrefixedString(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodeSkuRecord: genre: %w", err)
		}
		out.Genre = val
		off += n
	}
	{
		val, n, err := DecodePrefixedString(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodeSkuRecord: object_id: %w", err)
		}
		out.ObjectId = val
		off += n
	}
	{
		val, n, err := DecodePrefixedString(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodeSkuRecord: type_id: %w", err)
		}
		out.TypeId = val
		off += n
	}
	{
		val, n, err := DecodePrefixedStringList(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodeSkuRecord: tags: %w", err)
		}
		out.Tags = val
		off += n
	}
	{
		val, n, err := DecodePrefixedStringList(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodeSkuRecord: tags_implicit: %w", err)
		}
		out.TagsImplicit = val
		off += n
	}
	{
		val, n, err := DecodePrefixedString(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodeSkuRecord: blob_digest: %w", err)
		}
		out.BlobDigest = val
		off += n
	}
	{
		val, n, err := DecodePrefixedString(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodeSkuRecord: description: %w", err)
		}
		out.Description = val
		off += n
	}
	return out, off, nil
}

func EncodeSkuRecord(v *SkuRecord) ([]byte, error) {
	size := SizeSkuRecord(v)
	buf := make([]byte, size)
	off := 0
	{
		enc, err := EncodePrefixedString(&v.Genre)
		if err != nil {
			return nil, fmt.Errorf("EncodeSkuRecord: genre: %w", err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	{
		enc, err := EncodePrefixedString(&v.ObjectId)
		if err != nil {
			return nil, fmt.Errorf("EncodeSkuRecord: object_id: %w", err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	{
		enc, err := EncodePrefixedString(&v.TypeId)
		if err != nil {
			return nil, fmt.Errorf("EncodeSkuRecord: type_id: %w", err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	{
		enc, err := EncodePrefixedStringList(&v.Tags)
		if err != nil {
			return nil, fmt.Errorf("EncodeSkuRecord: tags: %w", err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	{
		enc, err := EncodePrefixedStringList(&v.TagsImplicit)
		if err != nil {
			return nil, fmt.Errorf("EncodeSkuRecord: tags_implicit: %w", err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	{
		enc, err := EncodePrefixedString(&v.BlobDigest)
		if err != nil {
			return nil, fmt.Errorf("EncodeSkuRecord: blob_digest: %w", err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	{
		enc, err := EncodePrefixedString(&v.Description)
		if err != nil {
			return nil, fmt.Errorf("EncodeSkuRecord: description: %w", err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	return buf, nil
}

func SizeSkuRecord(v *SkuRecord) int {
	size := 0
	size += SizePrefixedString(&v.Genre)
	size += SizePrefixedString(&v.ObjectId)
	size += SizePrefixedString(&v.TypeId)
	size += SizePrefixedStringList(&v.Tags)
	size += SizePrefixedStringList(&v.TagsImplicit)
	size += SizePrefixedString(&v.BlobDigest)
	size += SizePrefixedString(&v.Description)
	return size
}

type PrefixedString struct {
	Data []byte
}

func DecodePrefixedString(data []byte) (PrefixedString, int, error) {
	var out PrefixedString
	off := 0
	if len(data) < off+4 {
		return out, 0, fmt.Errorf("DecodePrefixedString: need %d bytes for len at offset %d, have %d", 4, off, len(data))
	}
	v_len := uint32(binary.LittleEndian.Uint32(data[off:]))
	off += 4
	if len(data) < off+int(v_len) {
		return out, 0, fmt.Errorf("DecodePrefixedString: need %d bytes for data at offset %d, have %d", v_len, off, len(data))
	}
	out.Data = make([]byte, v_len)
	copy(out.Data, data[off:off+int(v_len)])
	off += int(v_len)
	return out, off, nil
}

func EncodePrefixedString(v *PrefixedString) ([]byte, error) {
	size := SizePrefixedString(v)
	buf := make([]byte, size)
	off := 0
	binary.LittleEndian.PutUint32(buf[off:], uint32(uint32(len(v.Data))))
	off += 4
	copy(buf[off:], v.Data)
	off += len(v.Data)
	return buf, nil
}

func SizePrefixedString(v *PrefixedString) int {
	size := 0
	size += 4
	size += len(v.Data)
	return size
}

type PrefixedStringList struct {
	Items []PrefixedString
}

func DecodePrefixedStringList(data []byte) (PrefixedStringList, int, error) {
	var out PrefixedStringList
	off := 0
	if len(data) < off+4 {
		return out, 0, fmt.Errorf("DecodePrefixedStringList: need %d bytes for count at offset %d, have %d", 4, off, len(data))
	}
	v_count := uint32(binary.LittleEndian.Uint32(data[off:]))
	off += 4
	out.Items = make([]PrefixedString, v_count)
	for i := 0; i < int(v_count); i++ {
		item, n, err := DecodePrefixedString(data[off:])
		if err != nil {
			return out, 0, fmt.Errorf("DecodePrefixedStringList: items[%d]: %w", i, err)
		}
		out.Items[i] = item
		off += n
	}
	return out, off, nil
}

func EncodePrefixedStringList(v *PrefixedStringList) ([]byte, error) {
	size := SizePrefixedStringList(v)
	buf := make([]byte, size)
	off := 0
	binary.LittleEndian.PutUint32(buf[off:], uint32(uint32(len(v.Items))))
	off += 4
	for i := range v.Items {
		enc, err := EncodePrefixedString(&v.Items[i])
		if err != nil {
			return nil, fmt.Errorf("EncodePrefixedStringList: items[%d]: %w", i, err)
		}
		copy(buf[off:], enc)
		off += len(enc)
	}
	return buf, nil
}

func SizePrefixedStringList(v *PrefixedStringList) int {
	size := 0
	size += 4
	for i := range v.Items {
		size += SizePrefixedString(&v.Items[i])
	}
	return size
}
