// Code generated by langlang extract -mode=views; DO NOT EDIT.
// Grammar: /Users/sfriedenberg/eng/repos/langlang/.worktrees/light-rowan/docs/live/assets/examples/json/json.peg

package jsonviews

const (
	_nameID_Array   int32 = 21
	_nameID_Char    int32 = 24
	_nameID_EOF     int32 = 19
	_nameID_EOL     int32 = 34
	_nameID_Escape  int32 = 25
	_nameID_Exp     int32 = 31
	_nameID_Frac    int32 = 30
	_nameID_Hex     int32 = 27
	_nameID_Int     int32 = 29
	_nameID_JSON    int32 = 16
	_nameID_Member  int32 = 32
	_nameID_Number  int32 = 28
	_nameID_Object  int32 = 20
	_nameID_Space   int32 = 33
	_nameID_Spacing int32 = 17
	_nameID_String  int32 = 22
	_nameID_Unicode int32 = 26
	_nameID_Value   int32 = 18
)

// JSON is a read-only view over a JSON node.
// Child references are resolved once at construction time.
type JSON struct {
	t         *tree
	id        NodeID
	_value    NodeID
	_hasValue bool
	_eOF      NodeID
	_hasEOF   bool
}

// Text returns the full matched text of this node.
func (v JSON) Text() string {
	return v.t.UnsafeText(v.id)
}

func newJSON(t *tree, id NodeID) JSON {
	v := JSON{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			case _nameID_EOF:
				if !v._hasEOF {
					v._eOF = cid
					v._hasEOF = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		case _nameID_EOF:
			v._eOF = child
			v._hasEOF = true
		}
	}
	return v
}

// Value returns a view over the Value child.
func (v JSON) Value() (Value, bool) {
	if !v._hasValue {
		return Value{}, false
	}
	return Value{t: v.t, id: v._value}, true
}

// EOF returns the EOF text.
func (v JSON) EOF() string {
	if !v._hasEOF {
		return ""
	}
	return v.t.UnsafeText(v._eOF)
}

// Array is a read-only view over a Array node.
// Child references are resolved once at construction time.
type Array struct {
	t         *tree
	id        NodeID
	_value    NodeID
	_hasValue bool
}

// Text returns the full matched text of this node.
func (v Array) Text() string {
	return v.t.UnsafeText(v.id)
}

func newArray(t *tree, id NodeID) Array {
	v := Array{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		}
	}
	return v
}

// Value returns a view over the Value child.
func (v Array) Value() (Value, bool) {
	if !v._hasValue {
		return Value{}, false
	}
	return Value{t: v.t, id: v._value}, true
}

// char_view is a read-only view over a Char node.
type char_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v char_view) Text() string {
	return v.t.UnsafeText(v.id)
}

// Escape returns a escape_view if this alternative matched.
func (v char_view) Escape() (escape_view, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Escape) {
		return escape_view{}, false
	}
	return newEscape(v.t, child), true
}

// Unicode returns a unicode_view if this alternative matched.
func (v char_view) Unicode() (unicode_view, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Unicode) {
		return unicode_view{}, false
	}
	return newUnicode(v.t, child), true
}

// eOF_view is a read-only view over a EOF node.
type eOF_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v eOF_view) Text() string {
	return v.t.UnsafeText(v.id)
}

// eOL_view is a read-only view over a EOL node.
type eOL_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v eOL_view) Text() string {
	return v.t.UnsafeText(v.id)
}

// escape_view is a read-only view over a Escape node.
// Child references are resolved once at construction time.
type escape_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v escape_view) Text() string {
	return v.t.UnsafeText(v.id)
}

func newEscape(t *tree, id NodeID) escape_view {
	v := escape_view{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// exp_view is a read-only view over a Exp node.
// Child references are resolved once at construction time.
type exp_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v exp_view) Text() string {
	return v.t.UnsafeText(v.id)
}

func newExp(t *tree, id NodeID) exp_view {
	v := exp_view{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// frac_view is a read-only view over a Frac node.
// Child references are resolved once at construction time.
type frac_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v frac_view) Text() string {
	return v.t.UnsafeText(v.id)
}

func newFrac(t *tree, id NodeID) frac_view {
	v := frac_view{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// hex_view is a read-only view over a Hex node.
type hex_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v hex_view) Text() string {
	return v.t.UnsafeText(v.id)
}

// int_view is a read-only view over a Int node.
type int_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v int_view) Text() string {
	return v.t.UnsafeText(v.id)
}

// Member is a read-only view over a Member node.
// Child references are resolved once at construction time.
type Member struct {
	t          *tree
	id         NodeID
	_string    NodeID
	_hasString bool
	_value     NodeID
	_hasValue  bool
}

// Text returns the full matched text of this node.
func (v Member) Text() string {
	return v.t.UnsafeText(v.id)
}

func newMember(t *tree, id NodeID) Member {
	v := Member{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_String:
				if !v._hasString {
					v._string = cid
					v._hasString = true
				}
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_String:
			v._string = child
			v._hasString = true
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		}
	}
	return v
}

// String returns a view over the String child.
func (v Member) String() (String, bool) {
	if !v._hasString {
		return String{}, false
	}
	return newString(v.t, v._string), true
}

// Value returns a view over the Value child.
func (v Member) Value() (Value, bool) {
	if !v._hasValue {
		return Value{}, false
	}
	return Value{t: v.t, id: v._value}, true
}

// Number is a read-only view over a Number node.
// Child references are resolved once at construction time.
type Number struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v Number) Text() string {
	return v.t.UnsafeText(v.id)
}

func newNumber(t *tree, id NodeID) Number {
	v := Number{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// Object is a read-only view over a Object node.
// Child references are resolved once at construction time.
type Object struct {
	t          *tree
	id         NodeID
	_member    NodeID
	_hasMember bool
}

// Text returns the full matched text of this node.
func (v Object) Text() string {
	return v.t.UnsafeText(v.id)
}

func newObject(t *tree, id NodeID) Object {
	v := Object{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Member:
				if !v._hasMember {
					v._member = cid
					v._hasMember = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Member:
			v._member = child
			v._hasMember = true
		}
	}
	return v
}

// Member returns a view over the Member child.
func (v Object) Member() (Member, bool) {
	if !v._hasMember {
		return Member{}, false
	}
	return newMember(v.t, v._member), true
}

// space_view is a read-only view over a Space node.
type space_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v space_view) Text() string {
	return v.t.UnsafeText(v.id)
}

// spacing_view is a read-only view over a Spacing node.
type spacing_view struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v spacing_view) Text() string {
	return v.t.UnsafeText(v.id)
}

// String is a read-only view over a String node.
// Child references are resolved once at construction time.
type String struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v String) Text() string {
	return v.t.UnsafeText(v.id)
}

func newString(t *tree, id NodeID) String {
	v := String{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// unicode_view is a read-only view over a Unicode node.
// Child references are resolved once at construction time.
type unicode_view struct {
	t    *tree
	id   NodeID
	_hex []NodeID
}

// Text returns the full matched text of this node.
func (v unicode_view) Text() string {
	return v.t.UnsafeText(v.id)
}

func newUnicode(t *tree, id NodeID) unicode_view {
	v := unicode_view{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Hex:
				v._hex = append(v._hex, cid)
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Hex:
			v._hex = append(v._hex, child)
		}
	}
	return v
}

// HexCount returns the number of Hex children.
func (v unicode_view) HexCount() int {
	return len(v._hex)
}

// HexAt returns the text of the i-th Hex child.
func (v unicode_view) HexAt(i int) string {
	return v.t.UnsafeText(v._hex[i])
}

// Value is a read-only view over a Value node.
type Value struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v Value) Text() string {
	return v.t.UnsafeText(v.id)
}

// Object returns a Object if this alternative matched.
func (v Value) Object() (Object, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Object) {
		return Object{}, false
	}
	return newObject(v.t, child), true
}

// Array returns a Array if this alternative matched.
func (v Value) Array() (Array, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Array) {
		return Array{}, false
	}
	return newArray(v.t, child), true
}

// String returns a String if this alternative matched.
func (v Value) String() (String, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_String) {
		return String{}, false
	}
	return newString(v.t, child), true
}

// Number returns a Number if this alternative matched.
func (v Value) Number() (Number, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Number) {
		return Number{}, false
	}
	return newNumber(v.t, child), true
}
