// Code generated by langlang extract -mode=views; DO NOT EDIT.
// Grammar: /Users/sfriedenberg/eng/repos/langlang/.worktrees/light-rowan/docs/live/assets/examples/json/json.peg

package jsonviews

const (
	_nameID_Array            int32 = 21
	_nameID_Char             int32 = 24
	_nameID_EOF              int32 = 19
	_nameID_EOL              int32 = 34
	_nameID_Escape           int32 = 25
	_nameID_Exp              int32 = 31
	_nameID_Frac             int32 = 30
	_nameID_Hex              int32 = 27
	_nameID_Int              int32 = 29
	_nameID_JSON             int32 = 16
	_nameID_Member           int32 = 32
	_nameID_Number           int32 = 28
	_nameID_Object           int32 = 20
	_nameID_Space            int32 = 33
	_nameID_Spacing          int32 = 17
	_nameID_String           int32 = 22
	_nameID_Unicode          int32 = 26
	_nameID_Value            int32 = 18
	_nameID_arrayClose       int32 = 4
	_nameID_eof              int32 = 2
	_nameID_itemAfterComma   int32 = 3
	_nameID_jsonValue        int32 = 1
	_nameID_memberAfterComma int32 = 5
	_nameID_memberColon      int32 = 7
	_nameID_memberValue      int32 = 8
	_nameID_objectClose      int32 = 6
	_nameID_strClose         int32 = 11
)

// JSONView is a read-only view over a JSON node.
// Child references are resolved once at construction time.
type JSONView struct {
	t         *tree
	id        NodeID
	_value    NodeID
	_hasValue bool
	_eOF      NodeID
	_hasEOF   bool
}

// Text returns the full matched text of this node.
func (v JSONView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newJSONView(t *tree, id NodeID) JSONView {
	v := JSONView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			case _nameID_EOF:
				if !v._hasEOF {
					v._eOF = cid
					v._hasEOF = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		case _nameID_EOF:
			v._eOF = child
			v._hasEOF = true
		}
	}
	return v
}

// Value returns a view over the Value child.
func (v JSONView) Value() (ValueView, bool) {
	if !v._hasValue {
		return ValueView{}, false
	}
	return ValueView{t: v.t, id: v._value}, true
}

// EOF returns the EOF text.
func (v JSONView) EOF() string {
	if !v._hasEOF {
		return ""
	}
	return v.t.UnsafeText(v._eOF)
}

// ArrayView is a read-only view over a Array node.
// Child references are resolved once at construction time.
type ArrayView struct {
	t         *tree
	id        NodeID
	_value    NodeID
	_hasValue bool
}

// Text returns the full matched text of this node.
func (v ArrayView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newArrayView(t *tree, id NodeID) ArrayView {
	v := ArrayView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		}
	}
	return v
}

// Value returns a view over the Value child.
func (v ArrayView) Value() (ValueView, bool) {
	if !v._hasValue {
		return ValueView{}, false
	}
	return ValueView{t: v.t, id: v._value}, true
}

// CharView is a read-only view over a Char node.
type CharView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v CharView) Text() string {
	return v.t.UnsafeText(v.id)
}

// Escape returns a EscapeView if this alternative matched.
func (v CharView) Escape() (EscapeView, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Escape) {
		return EscapeView{}, false
	}
	return newEscapeView(v.t, child), true
}

// Unicode returns a UnicodeView if this alternative matched.
func (v CharView) Unicode() (UnicodeView, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Unicode) {
		return UnicodeView{}, false
	}
	return newUnicodeView(v.t, child), true
}

// EOFView is a read-only view over a EOF node.
type EOFView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v EOFView) Text() string {
	return v.t.UnsafeText(v.id)
}

// EOLView is a read-only view over a EOL node.
type EOLView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v EOLView) Text() string {
	return v.t.UnsafeText(v.id)
}

// EscapeView is a read-only view over a Escape node.
// Child references are resolved once at construction time.
type EscapeView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v EscapeView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newEscapeView(t *tree, id NodeID) EscapeView {
	v := EscapeView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// ExpView is a read-only view over a Exp node.
// Child references are resolved once at construction time.
type ExpView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v ExpView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newExpView(t *tree, id NodeID) ExpView {
	v := ExpView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// FracView is a read-only view over a Frac node.
// Child references are resolved once at construction time.
type FracView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v FracView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newFracView(t *tree, id NodeID) FracView {
	v := FracView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// HexView is a read-only view over a Hex node.
type HexView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v HexView) Text() string {
	return v.t.UnsafeText(v.id)
}

// IntView is a read-only view over a Int node.
type IntView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v IntView) Text() string {
	return v.t.UnsafeText(v.id)
}

// MemberView is a read-only view over a Member node.
// Child references are resolved once at construction time.
type MemberView struct {
	t          *tree
	id         NodeID
	_string    NodeID
	_hasString bool
	_value     NodeID
	_hasValue  bool
}

// Text returns the full matched text of this node.
func (v MemberView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newMemberView(t *tree, id NodeID) MemberView {
	v := MemberView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_String:
				if !v._hasString {
					v._string = cid
					v._hasString = true
				}
			case _nameID_Value:
				if !v._hasValue {
					v._value = cid
					v._hasValue = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_String:
			v._string = child
			v._hasString = true
		case _nameID_Value:
			v._value = child
			v._hasValue = true
		}
	}
	return v
}

// String returns a view over the String child.
func (v MemberView) String() (StringView, bool) {
	if !v._hasString {
		return StringView{}, false
	}
	return newStringView(v.t, v._string), true
}

// Value returns a view over the Value child.
func (v MemberView) Value() (ValueView, bool) {
	if !v._hasValue {
		return ValueView{}, false
	}
	return ValueView{t: v.t, id: v._value}, true
}

// NumberView is a read-only view over a Number node.
// Child references are resolved once at construction time.
type NumberView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v NumberView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newNumberView(t *tree, id NodeID) NumberView {
	v := NumberView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// ObjectView is a read-only view over a Object node.
// Child references are resolved once at construction time.
type ObjectView struct {
	t          *tree
	id         NodeID
	_member    NodeID
	_hasMember bool
}

// Text returns the full matched text of this node.
func (v ObjectView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newObjectView(t *tree, id NodeID) ObjectView {
	v := ObjectView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Member:
				if !v._hasMember {
					v._member = cid
					v._hasMember = true
				}
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Member:
			v._member = child
			v._hasMember = true
		}
	}
	return v
}

// Member returns a view over the Member child.
func (v ObjectView) Member() (MemberView, bool) {
	if !v._hasMember {
		return MemberView{}, false
	}
	return newMemberView(v.t, v._member), true
}

// SpaceView is a read-only view over a Space node.
type SpaceView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v SpaceView) Text() string {
	return v.t.UnsafeText(v.id)
}

// SpacingView is a read-only view over a Spacing node.
type SpacingView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v SpacingView) Text() string {
	return v.t.UnsafeText(v.id)
}

// StringView is a read-only view over a String node.
// Child references are resolved once at construction time.
type StringView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v StringView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newStringView(t *tree, id NodeID) StringView {
	v := StringView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// UnicodeView is a read-only view over a Unicode node.
// Child references are resolved once at construction time.
type UnicodeView struct {
	t    *tree
	id   NodeID
	_hex []NodeID
}

// Text returns the full matched text of this node.
func (v UnicodeView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newUnicodeView(t *tree, id NodeID) UnicodeView {
	v := UnicodeView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			case _nameID_Hex:
				v._hex = append(v._hex, cid)
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		case _nameID_Hex:
			v._hex = append(v._hex, child)
		}
	}
	return v
}

// HexCount returns the number of Hex children.
func (v UnicodeView) HexCount() int {
	return len(v._hex)
}

// HexAt returns the text of the i-th Hex child.
func (v UnicodeView) HexAt(i int) string {
	return v.t.UnsafeText(v._hex[i])
}

// ValueView is a read-only view over a Value node.
type ValueView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v ValueView) Text() string {
	return v.t.UnsafeText(v.id)
}

// Object returns a ObjectView if this alternative matched.
func (v ValueView) Object() (ObjectView, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Object) {
		return ObjectView{}, false
	}
	return newObjectView(v.t, child), true
}

// Array returns a ArrayView if this alternative matched.
func (v ValueView) Array() (ArrayView, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Array) {
		return ArrayView{}, false
	}
	return newArrayView(v.t, child), true
}

// String returns a StringView if this alternative matched.
func (v ValueView) String() (StringView, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_String) {
		return StringView{}, false
	}
	return newStringView(v.t, child), true
}

// Number returns a NumberView if this alternative matched.
func (v ValueView) Number() (NumberView, bool) {
	child, ok := v.t.Child(v.id)
	if !ok || !v.t.IsNamed(child, _nameID_Number) {
		return NumberView{}, false
	}
	return newNumberView(v.t, child), true
}

// arrayCloseView is a read-only view over a arrayClose node.
// Child references are resolved once at construction time.
type arrayCloseView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v arrayCloseView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newarrayCloseView(t *tree, id NodeID) arrayCloseView {
	v := arrayCloseView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// eofView is a read-only view over a eof node.
type eofView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v eofView) Text() string {
	return v.t.UnsafeText(v.id)
}

// itemAfterCommaView is a read-only view over a itemAfterComma node.
type itemAfterCommaView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v itemAfterCommaView) Text() string {
	return v.t.UnsafeText(v.id)
}

// jsonValueView is a read-only view over a jsonValue node.
// Child references are resolved once at construction time.
type jsonValueView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v jsonValueView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newjsonValueView(t *tree, id NodeID) jsonValueView {
	v := jsonValueView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// memberAfterCommaView is a read-only view over a memberAfterComma node.
type memberAfterCommaView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v memberAfterCommaView) Text() string {
	return v.t.UnsafeText(v.id)
}

// memberColonView is a read-only view over a memberColon node.
// Child references are resolved once at construction time.
type memberColonView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v memberColonView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newmemberColonView(t *tree, id NodeID) memberColonView {
	v := memberColonView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// memberValueView is a read-only view over a memberValue node.
type memberValueView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v memberValueView) Text() string {
	return v.t.UnsafeText(v.id)
}

// objectCloseView is a read-only view over a objectClose node.
// Child references are resolved once at construction time.
type objectCloseView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v objectCloseView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newobjectCloseView(t *tree, id NodeID) objectCloseView {
	v := objectCloseView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}

// strCloseView is a read-only view over a strClose node.
// Child references are resolved once at construction time.
type strCloseView struct {
	t  *tree
	id NodeID
}

// Text returns the full matched text of this node.
func (v strCloseView) Text() string {
	return v.t.UnsafeText(v.id)
}

func newstrCloseView(t *tree, id NodeID) strCloseView {
	v := strCloseView{t: t, id: id}
	child, ok := t.Child(id)
	if !ok {
		return v
	}
	if t.Type(child) == NodeType_Sequence {
		cr := t.childRanges[t.nodes[child].childID]
		for i := cr.start; i < cr.end; i++ {
			cid := t.children[i]
			if t.Type(cid) != NodeType_Node {
				continue
			}
			switch t.NameID(cid) {
			}
		}
	} else if t.Type(child) == NodeType_Node {
		switch t.NameID(child) {
		}
	}
	return v
}
