package extract

import (
	"bytes"
	"strings"
	"unicode"

	jen "github.com/dave/jennifer/jen"

	"github.com/clarete/langlang/go/junction"
)

// junctionPkg is the import path for the junction package.
const junctionPkg = "github.com/clarete/langlang/go/junction"

// RenderArenaFileJen produces a formatted Go source file containing
// per-type arena infrastructure and arena-backed extraction functions.
// It also emits a ScannerSpec and an Estimate function that uses
// junction hit counts to pre-size arenas without walking the parsed tree.
func RenderArenaFileJen(
	pkg, grammarPath string,
	nameIDs []NameIDEntry,
	structs []StructInfo,
	rules map[string]RuleInfo,
	spec junction.ScannerSpec,
) (string, error) {
	f := jen.NewFile(pkg)
	f.HeaderComment("Code generated by langlang extract -arena (jen); DO NOT EDIT.")
	f.HeaderComment("Grammar: " + grammarPath)

	arenaName := ucFirst(pkg) + "Arenas"
	countsName := ucFirst(pkg) + "NodeCounts"

	// nameID constants
	f.Const().DefsFunc(func(g *jen.Group) {
		for _, n := range nameIDs {
			g.Id("_arenaNameID_" + n.Name).Id("int32").Op("=").Lit(int(n.ID))
		}
	})

	emitArenaStruct(f, arenaName, structs)
	emitNodeCountsStruct(f, countsName, structs)
	emitScannerSpec(f, pkg, spec)
	emitEstimateFunction(f, pkg, countsName, structs, rules, spec)
	emitAllocMethod(f, arenaName, countsName, structs)
	emitResetMethod(f, arenaName, structs)
	emitAllocStringMethod(f, arenaName)

	for _, si := range structs {
		emitArenaExtractFunctionJen(f, si, rules, arenaName)
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return "", err
	}
	return buf.String(), nil
}

// emitScannerSpec emits a package-level ScannerSpec var derived from the grammar.
func emitScannerSpec(f *jen.File, pkg string, spec junction.ScannerSpec) {
	varName := ucFirst(pkg) + "ArenaScanSpec"

	f.Var().Id(varName).Op("=").Qual(junctionPkg, "ScannerSpec").Values(jen.Dict{
		jen.Id("Junctions"): jen.Index().Qual(junctionPkg, "JunctionByte").ValuesFunc(func(g *jen.Group) {
			for _, jb := range spec.Junctions {
				g.Values(jen.Dict{
					jen.Id("Byte"): jen.LitRune(rune(jb.Byte)),
					jen.Id("Kind"): jen.Qual(junctionPkg, junctionKindName(jb.Kind)),
				})
			}
		}),
		jen.Id("Sequences"): jen.Index().Qual(junctionPkg, "JunctionSequence").ValuesFunc(func(g *jen.Group) {
			for _, seq := range spec.Sequences {
				g.Values(jen.Dict{
					jen.Id("Pattern"): jen.Index().Byte().Values(byteLits(seq.Pattern)...),
					jen.Id("Kind"):    jen.Qual(junctionPkg, junctionKindName(seq.Kind)),
				})
			}
		}),
		jen.Id("Quoting"): jen.Index().Qual(junctionPkg, "QuotingContext").ValuesFunc(func(g *jen.Group) {
			for _, qc := range spec.Quoting {
				g.Values(jen.Dict{
					jen.Id("Delimiter"):    jen.LitRune(rune(qc.Delimiter)),
					jen.Id("EscapePrefix"): jen.LitRune(rune(qc.EscapePrefix)),
				})
			}
		}),
	})
}

func junctionKindName(k junction.JunctionKind) string {
	switch k {
	case junction.JunctionOpen:
		return "JunctionOpen"
	case junction.JunctionClose:
		return "JunctionClose"
	case junction.JunctionSeparator:
		return "JunctionSeparator"
	}
	return "JunctionOpen"
}

func byteLits(bs []byte) []jen.Code {
	out := make([]jen.Code, len(bs))
	for i, b := range bs {
		out[i] = jen.LitRune(rune(b))
	}
	return out
}

// emitEstimateFunction generates a function that maps junction.HitCounts
// to per-type node count estimates. The mapping is derived by cross-referencing
// the grammar's bracket sequences with the struct field analysis.
func emitEstimateFunction(
	f *jen.File,
	pkg, countsName string,
	structs []StructInfo,
	rules map[string]RuleInfo,
	spec junction.ScannerSpec,
) {
	funcName := "Estimate" + ucFirst(pkg) + "NodeCounts"

	// Build the junction byte → struct mapping by examining which grammar
	// rules use which bracket bytes as their opening delimiter.
	type byteMapping struct {
		byte_     byte
		kind      junction.JunctionKind
		structIdx int    // index into structs, or -1
		fieldName string // for counting (pluralized struct name)
	}

	// Map open bracket bytes to the struct whose grammar rule starts with that byte.
	openToStruct := map[byte]int{} // byte → struct index
	for i, si := range structs {
		if rule, ok := rules[si.Name]; ok && rule.Kind == RuleSequence {
			for _, child := range rule.Children {
				if child.IsLiteral && len(child.RuleName) == 1 {
					b := child.RuleName[0]
					// Check if this byte is a junction Open
					for _, jb := range spec.Junctions {
						if jb.Byte == b && jb.Kind == junction.JunctionOpen {
							openToStruct[b] = i
						}
					}
				}
				break // only check first literal
			}
		}
	}

	// Count separator bytes for child slice estimation
	sepBytes := map[byte]bool{}
	for _, jb := range spec.Junctions {
		if jb.Kind == junction.JunctionSeparator {
			sepBytes[jb.Byte] = true
		}
	}

	f.Func().Id(funcName).Params(
		jen.Id("hc").Qual(junctionPkg, "HitCounts"),
	).Id(countsName).BlockFunc(func(g *jen.Group) {
		g.Var().Id("c").Id(countsName)

		// For each open bracket that maps to a struct, count hits
		for b, idx := range openToStruct {
			si := structs[idx]
			g.Id("c").Dot(pluralize(si.Name)).Op("=").Id("hc").Dot("ByByte").Index(jen.LitRune(rune(b)))
		}

		// Total separators + opens gives an upper bound on child counts
		// Strings estimate: all separators + all opens (generous upper bound)
		g.Comment("Upper-bound estimates for child slices and string pointers.")
		g.Id("totalSeps").Op(":=").Id("hc").Dot("Seps")
		g.Id("totalOpens").Op(":=").Id("hc").Dot("Opens")

		// For structs not directly mapped to a bracket byte, estimate from
		// separator counts (e.g., Members ≈ colons, Values ≈ seps + opens)
		for i, si := range structs {
			if _, mapped := openToStruct[byte(0)]; mapped && i == openToStruct[byte(0)] {
				continue // already mapped above
			}
			alreadyMapped := false
			for _, idx := range openToStruct {
				if idx == i {
					alreadyMapped = true
					break
				}
			}
			if alreadyMapped {
				continue
			}
			// Unmapped structs: estimate as totalSeps + totalOpens
			g.Id("c").Dot(pluralize(si.Name)).Op("=").Id("totalSeps").Op("+").Id("totalOpens")
		}

		g.Id("c").Dot("Strings").Op("=").Id("totalSeps").Op("+").Id("totalOpens").Op("+").Lit(1)

		g.Return(jen.Id("c"))
	})
}

// emitArenaStruct generates the Arenas struct with per-type slices,
// backing buffers for slice fields, and a string buffer.
func emitArenaStruct(f *jen.File, arenaName string, structs []StructInfo) {
	f.Type().Id(arenaName).StructFunc(func(g *jen.Group) {
		// Per-type slices
		for _, si := range structs {
			g.Id(pluralize(si.Name)).Index().Id(si.Name)
		}
		// Backing buffers for slice fields (named by parent+field to avoid collisions)
		for _, si := range structs {
			for _, field := range si.Fields {
				if field.Kind == FieldSlice {
					g.Id(si.Name + field.GoName + "Buf").Index().Id(field.ElemType)
				}
			}
		}
		// String buffer
		g.Id("StringBuf").Index().String()
	})
}

// emitNodeCountsStruct generates the NodeCounts struct.
func emitNodeCountsStruct(f *jen.File, countsName string, structs []StructInfo) {
	f.Type().Id(countsName).StructFunc(func(g *jen.Group) {
		for _, si := range structs {
			g.Id(pluralize(si.Name)).Int()
		}
		g.Id("Strings").Int()
	})
}

// emitAllocMethod generates the Alloc method.
func emitAllocMethod(f *jen.File, arenaName, countsName string, structs []StructInfo) {
	f.Func().Params(jen.Id("a").Op("*").Id(arenaName)).Id("Alloc").Params(
		jen.Id("c").Id(countsName),
	).BlockFunc(func(g *jen.Group) {
		for _, si := range structs {
			field := pluralize(si.Name)
			g.Id("a").Dot(field).Op("=").Make(jen.Index().Id(si.Name), jen.Lit(0), jen.Id("c").Dot(field))
		}
		// Backing buffers — use the same capacity as their source type
		for _, si := range structs {
			for _, field := range si.Fields {
				if field.Kind == FieldSlice {
					// The backing buffer capacity is the count of the element type
					g.Id("a").Dot(si.Name+field.GoName+"Buf").Op("=").Make(
						jen.Index().Id(field.ElemType), jen.Lit(0),
						jen.Id("c").Dot(pluralize(field.ElemType)),
					)
				}
			}
		}
		g.Id("a").Dot("StringBuf").Op("=").Make(jen.Index().String(), jen.Lit(0), jen.Id("c").Dot("Strings"))
	})
}

// emitResetMethod generates the Reset method.
func emitResetMethod(f *jen.File, arenaName string, structs []StructInfo) {
	f.Func().Params(jen.Id("a").Op("*").Id(arenaName)).Id("Reset").Params().BlockFunc(func(g *jen.Group) {
		for _, si := range structs {
			field := pluralize(si.Name)
			g.Id("a").Dot(field).Op("=").Id("a").Dot(field).Index(jen.Empty(), jen.Lit(0))
		}
		for _, si := range structs {
			for _, field := range si.Fields {
				if field.Kind == FieldSlice {
					bufName := si.Name + field.GoName + "Buf"
					g.Id("a").Dot(bufName).Op("=").Id("a").Dot(bufName).Index(jen.Empty(), jen.Lit(0))
				}
			}
		}
		g.Id("a").Dot("StringBuf").Op("=").Id("a").Dot("StringBuf").Index(jen.Empty(), jen.Lit(0))
	})
}

// emitAllocStringMethod generates the allocString helper.
func emitAllocStringMethod(f *jen.File, arenaName string) {
	f.Func().Params(jen.Id("a").Op("*").Id(arenaName)).Id("allocString").Params(
		jen.Id("s").String(),
	).Op("*").String().BlockFunc(func(g *jen.Group) {
		g.Id("idx").Op(":=").Len(jen.Id("a").Dot("StringBuf"))
		g.Id("a").Dot("StringBuf").Op("=").Append(jen.Id("a").Dot("StringBuf"), jen.Id("s"))
		g.Return(jen.Op("&").Id("a").Dot("StringBuf").Index(jen.Id("idx")))
	})
}

// emitArenaExtractFunctionJen generates an arena-backed extraction function.
func emitArenaExtractFunctionJen(f *jen.File, si StructInfo, rules map[string]RuleInfo, arenaName string) {
	funcName := "Extract" + si.Name + "Arena"
	sliceField := pluralize(si.Name)

	f.Func().Id(funcName).Params(
		jen.Id("t").Op("*").Id("tree"),
		jen.Id("id").Id("NodeID"),
		jen.Id("a").Op("*").Id(arenaName),
	).Params(
		jen.Op("*").Id(si.Name),
		jen.Error(),
	).BlockFunc(func(g *jen.Group) {
		// idx := len(a.Slice)
		g.Id("idx").Op(":=").Len(jen.Id("a").Dot(sliceField))
		// a.Slice = append(a.Slice, Type{})
		g.Id("a").Dot(sliceField).Op("=").Append(
			jen.Id("a").Dot(sliceField),
			jen.Id(si.Name).Values(),
		)

		if isChoiceStruct(&si) {
			emitArenaChoiceBodyJen(g, si, rules, arenaName, sliceField)
		} else {
			emitArenaSequenceBodyJen(g, si, rules, arenaName, sliceField)
		}

		// return &a.Slice[idx], nil
		g.Return(jen.Op("&").Id("a").Dot(sliceField).Index(jen.Id("idx")), jen.Nil())
	})
}

func emitArenaChoiceBodyJen(g *jen.Group, si StructInfo, rules map[string]RuleInfo, arenaName, sliceField string) {
	g.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("t").Dot("Child").Call(jen.Id("id"))
	g.If(jen.Op("!").Id("ok")).Block(
		jen.Return(
			jen.Op("&").Id("a").Dot(sliceField).Index(jen.Id("idx")),
			jen.Qual("fmt", "Errorf").Call(jen.Lit(si.Name+": no child")),
		),
	)

	g.Switch().BlockFunc(func(sw *jen.Group) {
		for _, f := range si.Fields {
			if f.Kind != FieldOptional {
				continue
			}
			innerType := strings.TrimPrefix(f.GoType, "*")

			sw.Case(
				jen.Id("t").Dot("IsNamed").Call(jen.Id("child"), jen.Id("_arenaNameID_"+f.LLTag)),
			).BlockFunc(func(body *jen.Group) {
				if innerType == "string" {
					body.Id("a").Dot(sliceField).Index(jen.Id("idx")).Dot(f.GoName).Op("=").
						Id("a").Dot("allocString").Call(jen.Id("t").Dot("Text").Call(jen.Id("child")))
				} else {
					body.List(jen.Id("val"), jen.Id("err")).Op(":=").
						Id("Extract"+innerType+"Arena").Call(jen.Id("t"), jen.Id("child"), jen.Id("a"))
					body.If(jen.Id("err").Op("!=").Nil()).Block(
						jen.Return(jen.Op("&").Id("a").Dot(sliceField).Index(jen.Id("idx")), jen.Id("err")),
					)
					body.Id("a").Dot(sliceField).Index(jen.Id("idx")).Dot(f.GoName).Op("=").Id("val")
				}
			})
		}

		sw.Case(
			jen.Id("t").Dot("Type").Call(jen.Id("child")).Op("==").Id("NodeType_String"),
		).Block(
			jen.Comment("literal alternative"),
		)
	})
}

func emitArenaSequenceBodyJen(g *jen.Group, si StructInfo, rules map[string]RuleInfo, arenaName, sliceField string) {
	// Separate slice fields (need two-pass: count + fill) from non-slice fields.
	var sliceFields, nonSliceFields []FieldInfo
	for _, f := range si.Fields {
		if f.Kind == FieldSlice {
			sliceFields = append(sliceFields, f)
		} else {
			nonSliceFields = append(nonSliceFields, f)
		}
	}

	// For slice fields: count children, reserve, fill.
	for _, sf := range sliceFields {
		bufName := si.Name + sf.GoName + "Buf"
		countVar := "count" + sf.GoName

		// Count children
		g.Var().Id(countVar).Int()
		g.Id("t").Dot("Visit").Call(
			jen.Id("id"),
			jen.Func().Params(jen.Id("cid").Id("NodeID")).Bool().Block(
				jen.If(jen.Id("cid").Op("==").Id("id")).Block(jen.Return(jen.True())),
				jen.If(jen.Id("t").Dot("Type").Call(jen.Id("cid")).Op("!=").Id("NodeType_Node")).Block(jen.Return(jen.True())),
				jen.If(jen.Id("t").Dot("NameID").Call(jen.Id("cid")).Op("==").Id("_arenaNameID_"+sf.LLTag)).Block(
					jen.Id(countVar).Op("++"),
					jen.Return(jen.False()),
				),
				jen.Return(jen.True()),
			),
		)

		// Reserve contiguous slots
		startVar := "start" + sf.GoName
		g.Id(startVar).Op(":=").Len(jen.Id("a").Dot(bufName))
		g.Id("a").Dot(bufName).Op("=").Append(
			jen.Id("a").Dot(bufName),
			jen.Make(jen.Index().Id(sf.ElemType), jen.Id(countVar)).Op("..."),
		)
		sliceVar := "slice" + sf.GoName
		g.Id(sliceVar).Op(":=").Id("a").Dot(bufName).Index(
			jen.Id(startVar), jen.Id(startVar).Op("+").Id(countVar),
		)

		// Fill with extraction
		iVar := "i" + sf.GoName
		g.Var().Id(iVar).Int()
		g.Id("t").Dot("Visit").Call(
			jen.Id("id"),
			jen.Func().Params(jen.Id("cid").Id("NodeID")).Bool().BlockFunc(func(v *jen.Group) {
				v.If(jen.Id("cid").Op("==").Id("id")).Block(jen.Return(jen.True()))
				v.If(jen.Id("t").Dot("Type").Call(jen.Id("cid")).Op("!=").Id("NodeType_Node")).Block(jen.Return(jen.True()))
				v.If(jen.Id("t").Dot("NameID").Call(jen.Id("cid")).Op("==").Id("_arenaNameID_" + sf.LLTag)).BlockFunc(func(body *jen.Group) {
					body.List(jen.Id("val"), jen.Id("err")).Op(":=").
						Id("Extract"+sf.ElemType+"Arena").Call(jen.Id("t"), jen.Id("cid"), jen.Id("a"))
					body.If(jen.Id("err").Op("==").Nil()).Block(
						jen.Id(sliceVar).Index(jen.Id(iVar)).Op("=").Op("*").Id("val"),
						jen.Id(iVar).Op("++"),
					)
					body.Return(jen.False())
				})
				v.Return(jen.True())
			}),
		)

		// Assign the sub-slice to the struct field (re-derive for pointer stability)
		g.Id("a").Dot(sliceField).Index(jen.Id("idx")).Dot(sf.GoName).Op("=").
			Id(sliceVar).Index(jen.Empty(), jen.Id(iVar))
	}

	// For non-slice fields: single Visit
	if len(nonSliceFields) > 0 {
		g.Id("t").Dot("Visit").Call(
			jen.Id("id"),
			jen.Func().Params(jen.Id("cid").Id("NodeID")).Bool().BlockFunc(func(v *jen.Group) {
				v.If(jen.Id("cid").Op("==").Id("id")).Block(jen.Return(jen.True()))
				v.If(jen.Id("t").Dot("Type").Call(jen.Id("cid")).Op("!=").Id("NodeType_Node")).Block(jen.Return(jen.True()))

				v.Switch(jen.Id("t").Dot("NameID").Call(jen.Id("cid"))).BlockFunc(func(sw *jen.Group) {
					for _, f := range nonSliceFields {
						emitArenaSequenceCaseJen(sw, f, sliceField)
					}
				})

				v.Return(jen.True())
			}),
		)
	}
}

func emitArenaSequenceCaseJen(sw *jen.Group, f FieldInfo, sliceField string) {
	nameID := jen.Id("_arenaNameID_" + f.LLTag)

	switch f.Kind {
	case FieldText:
		sw.Case(nameID).BlockFunc(func(body *jen.Group) {
			body.Id("a").Dot(sliceField).Index(jen.Id("idx")).Dot(f.GoName).Op("=").
				Id("t").Dot("Text").Call(jen.Id("cid"))
			body.Return(jen.False())
		})

	case FieldNamedRule:
		sw.Case(nameID).BlockFunc(func(body *jen.Group) {
			body.List(jen.Id("val"), jen.Id("err")).Op(":=").
				Id("Extract"+f.GoType+"Arena").Call(jen.Id("t"), jen.Id("cid"), jen.Id("a"))
			body.If(jen.Id("err").Op("==").Nil()).Block(
				jen.Id("a").Dot(sliceField).Index(jen.Id("idx")).Dot(f.GoName).Op("=").Op("*").Id("val"),
			)
			body.Return(jen.False())
		})

	case FieldOptional:
		innerType := strings.TrimPrefix(f.GoType, "*")
		sw.Case(nameID).BlockFunc(func(body *jen.Group) {
			if innerType == "string" {
				body.Id("a").Dot(sliceField).Index(jen.Id("idx")).Dot(f.GoName).Op("=").
					Id("a").Dot("allocString").Call(jen.Id("t").Dot("Text").Call(jen.Id("cid")))
			} else {
				body.List(jen.Id("val"), jen.Id("err")).Op(":=").
					Id("Extract"+innerType+"Arena").Call(jen.Id("t"), jen.Id("cid"), jen.Id("a"))
				body.If(jen.Id("err").Op("==").Nil()).Block(
					jen.Id("a").Dot(sliceField).Index(jen.Id("idx")).Dot(f.GoName).Op("=").Id("val"),
				)
			}
			body.Return(jen.False())
		})
	}
}

func pluralize(name string) string {
	lower := strings.ToLower(name)
	if strings.HasSuffix(lower, "y") && !strings.HasSuffix(lower, "ay") &&
		!strings.HasSuffix(lower, "ey") && !strings.HasSuffix(lower, "oy") {
		return name[:len(name)-1] + "ies"
	}
	if strings.HasSuffix(lower, "s") || strings.HasSuffix(lower, "x") ||
		strings.HasSuffix(lower, "sh") || strings.HasSuffix(lower, "ch") {
		return name + "es"
	}
	return name + "s"
}

func ucFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}
