package extract

import (
	"bytes"
	"strings"

	jen "github.com/dave/jennifer/jen"
)

// RenderFileJen produces a formatted Go source file using the jennifer library.
// It is functionally equivalent to RenderFile but builds the AST programmatically
// instead of using string concatenation and text/template.
func RenderFileJen(
	pkg, grammarPath string,
	nameIDs []NameIDEntry,
	structs []StructInfo,
	rules map[string]RuleInfo,
) (string, error) {
	f := jen.NewFile(pkg)
	f.HeaderComment("Code generated by langlang extract (jen); DO NOT EDIT.")
	f.HeaderComment("Grammar: " + grammarPath)

	// nameID constants
	f.Const().DefsFunc(func(g *jen.Group) {
		for _, n := range nameIDs {
			g.Id("_nameID_" + n.Name).Id("int32").Op("=").Lit(int(n.ID))
		}
	})

	// extraction functions
	for _, si := range structs {
		emitExtractFunctionJen(f, si, rules)
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func emitExtractFunctionJen(f *jen.File, si StructInfo, rules map[string]RuleInfo) {
	funcName := "Extract" + si.Name

	f.Func().Id(funcName).Params(
		jen.Id("t").Op("*").Id("tree"),
		jen.Id("id").Id("NodeID"),
	).Params(
		jen.Id(si.Name),
		jen.Error(),
	).BlockFunc(func(g *jen.Group) {
		g.Var().Id("out").Id(si.Name)

		if isChoiceStruct(&si) {
			emitChoiceBodyJen(g, si, rules)
		} else {
			emitSequenceBodyJen(g, si, rules)
		}

		g.Return(jen.Id("out"), jen.Nil())
	})
}

func emitChoiceBodyJen(g *jen.Group, si StructInfo, rules map[string]RuleInfo) {
	// child, ok := t.Child(id)
	g.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("t").Dot("Child").Call(jen.Id("id"))

	// if !ok { return out, fmt.Errorf("...") }
	g.If(jen.Op("!").Id("ok")).Block(
		jen.Return(jen.Id("out"), jen.Qual("fmt", "Errorf").Call(jen.Lit(si.Name+": no child"))),
	)

	// switch { case ... }
	g.Switch().BlockFunc(func(sw *jen.Group) {
		for _, f := range si.Fields {
			if f.Kind != FieldOptional {
				continue
			}
			innerType := strings.TrimPrefix(f.GoType, "*")

			sw.Case(
				jen.Id("t").Dot("IsNamed").Call(jen.Id("child"), jen.Id("_nameID_"+f.LLTag)),
			).BlockFunc(func(body *jen.Group) {
				if innerType == "string" {
					body.Id("s").Op(":=").Id("t").Dot("Text").Call(jen.Id("child"))
					body.Id("out").Dot(f.GoName).Op("=").Op("&").Id("s")
				} else {
					body.List(jen.Id("val"), jen.Id("err")).Op(":=").Id("Extract"+innerType).Call(
						jen.Id("t"), jen.Id("child"),
					)
					body.If(jen.Id("err").Op("!=").Nil()).Block(
						jen.Return(jen.Id("out"), jen.Id("err")),
					)
					body.Id("out").Dot(f.GoName).Op("=").Op("&").Id("val")
				}
			})
		}

		// literal alternative case
		sw.Case(
			jen.Id("t").Dot("Type").Call(jen.Id("child")).Op("==").Id("NodeType_String"),
		).Block(
			jen.Comment("literal alternative (e.g., 'true', 'false', 'null')"),
		)
	})
}

func emitSequenceBodyJen(g *jen.Group, si StructInfo, rules map[string]RuleInfo) {
	// t.Visit(id, func(cid NodeID) bool { ... })
	g.Id("t").Dot("Visit").Call(
		jen.Id("id"),
		jen.Func().Params(jen.Id("cid").Id("NodeID")).Bool().BlockFunc(func(v *jen.Group) {
			// if cid == id { return true }
			v.If(jen.Id("cid").Op("==").Id("id")).Block(
				jen.Return(jen.True()),
			)
			// if t.Type(cid) != NodeType_Node { return true }
			v.If(jen.Id("t").Dot("Type").Call(jen.Id("cid")).Op("!=").Id("NodeType_Node")).Block(
				jen.Return(jen.True()),
			)

			// switch t.NameID(cid) { ... }
			v.Switch(jen.Id("t").Dot("NameID").Call(jen.Id("cid"))).BlockFunc(func(sw *jen.Group) {
				for _, f := range si.Fields {
					emitSequenceCaseJen(sw, f)
				}
			})

			v.Return(jen.True())
		}),
	)
}

func emitSequenceCaseJen(sw *jen.Group, f FieldInfo) {
	nameID := jen.Id("_nameID_" + f.LLTag)

	switch f.Kind {
	case FieldText:
		sw.Case(nameID).BlockFunc(func(body *jen.Group) {
			body.Id("out").Dot(f.GoName).Op("=").Id("t").Dot("Text").Call(jen.Id("cid"))
			body.Return(jen.False())
		})

	case FieldNamedRule:
		sw.Case(nameID).BlockFunc(func(body *jen.Group) {
			body.List(jen.Id("val"), jen.Id("err")).Op(":=").Id("Extract"+f.GoType).Call(
				jen.Id("t"), jen.Id("cid"),
			)
			body.If(jen.Id("err").Op("==").Nil()).Block(
				jen.Id("out").Dot(f.GoName).Op("=").Id("val"),
			)
			body.Return(jen.False())
		})

	case FieldSlice:
		sw.Case(nameID).BlockFunc(func(body *jen.Group) {
			body.List(jen.Id("val"), jen.Id("err")).Op(":=").Id("Extract"+f.ElemType).Call(
				jen.Id("t"), jen.Id("cid"),
			)
			body.If(jen.Id("err").Op("==").Nil()).Block(
				jen.Id("out").Dot(f.GoName).Op("=").Append(jen.Id("out").Dot(f.GoName), jen.Id("val")),
			)
			body.Return(jen.False())
		})

	case FieldOptional:
		innerType := strings.TrimPrefix(f.GoType, "*")
		sw.Case(nameID).BlockFunc(func(body *jen.Group) {
			if innerType == "string" {
				body.Id("s").Op(":=").Id("t").Dot("Text").Call(jen.Id("cid"))
				body.Id("out").Dot(f.GoName).Op("=").Op("&").Id("s")
			} else {
				body.List(jen.Id("val"), jen.Id("err")).Op(":=").Id("Extract"+innerType).Call(
					jen.Id("t"), jen.Id("cid"),
				)
				body.If(jen.Id("err").Op("==").Nil()).Block(
					jen.Id("out").Dot(f.GoName).Op("=").Op("&").Id("val"),
				)
			}
			body.Return(jen.False())
		})
	}
}
