package extract

import (
	"bytes"
	"strings"
	"unicode"

	jen "github.com/dave/jennifer/jen"
)

// RenderViewsFileJen produces a formatted Go source file containing nameID
// constants and zero-allocation view types, using the jennifer library.
// It is functionally equivalent to RenderViewsFile.
func RenderViewsFileJen(
	pkg, grammarPath string,
	rules map[string]RuleInfo,
	rootRule string,
) (string, error) {
	f := jen.NewFile(pkg)
	f.HeaderComment("Code generated by langlang extract -mode=views (jen); DO NOT EDIT.")
	f.HeaderComment("Grammar: " + grammarPath)

	// nameID constants
	nameIDs := collectViewNameIDs(rules)
	f.Const().DefsFunc(func(g *jen.Group) {
		for _, n := range nameIDs {
			g.Id("_nameID_" + n.Name).Id("int32").Op("=").Lit(int(n.ID))
		}
	})

	exported := reachableFromRoot(rules, rootRule)
	ordered := orderRules(rules, rootRule)

	for _, name := range ordered {
		ri := rules[name]
		emitViewTypeJen(f, ri, rules, exported)
	}

	if rootRule != "" {
		if ri, ok := rules[rootRule]; ok && exported[rootRule] {
			emitPublicConstructorJen(f, ri)
		}
	}

	var buf bytes.Buffer
	if err := f.Render(&buf); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func emitViewTypeJen(f *jen.File, ri RuleInfo, rules map[string]RuleInfo, exported map[string]bool) {
	if ri.NameID < 0 || !unicode.IsUpper(rune(ri.Name[0])) {
		return
	}

	switch ri.Kind {
	case RuleSequence:
		emitSequenceViewJen(f, ri, rules, exported)
	case RuleChoice:
		emitChoiceViewJen(f, ri, rules, exported)
	case RuleRepeat:
		emitRepeatViewJen(f, ri, rules, exported)
	case RuleAlias:
		emitAliasViewJen(f, ri, rules, exported)
	case RuleOptional:
		emitAliasViewJen(f, ri, rules, exported)
	case RuleLeaf:
		viewName := viewTypeName(ri.Name, exported)
		emitViewStructJen(f, viewName, ri.Name)
		emitTextMethodJen(f, viewName)
	}
}

// viewLit builds a struct literal T{t: tExpr, id: idExpr} that jennifer renders
// on a single line (unlike jen.Dict which alphabetizes keys and goes multi-line).
func viewLit(typeName string, tExpr, idExpr jen.Code) jen.Code {
	return jen.Id(typeName).Values(
		jen.Id("t").Op(":").Add(tExpr),
		jen.Id("id").Op(":").Add(idExpr),
	)
}

// emitViewStructJen generates the basic view struct: type T struct { t *tree; id NodeID }
func emitViewStructJen(f *jen.File, viewName, ruleName string) {
	f.Comment(viewName + " is a read-only view over a " + ruleName + " node.")
	f.Type().Id(viewName).Struct(
		jen.Id("t").Op("*").Id("tree"),
		jen.Id("id").Id("NodeID"),
	)
}

// emitTextMethodJen generates: func (v T) String() string { return v.t.Text(v.id) }
func emitTextMethodJen(f *jen.File, viewName string) {
	f.Comment("String returns the full matched text of this node.")
	f.Func().Params(jen.Id("v").Id(viewName)).Id("String").Params().String().Block(
		jen.Return(jen.Id("v").Dot("t").Dot("Text").Call(jen.Id("v").Dot("id"))),
	)
}

func emitPublicConstructorJen(f *jen.File, ri RuleInfo) {
	typeName := ri.Name
	f.Comment("New" + typeName + " creates a " + typeName + " view from a parsed tree.")
	f.Func().Id("New"+typeName).Params(
		jen.Id("t").Id("Tree"),
	).Id(typeName).Block(
		jen.List(jen.Id("root"), jen.Id("ok")).Op(":=").Id("t").Dot("Root").Call(),
		jen.If(jen.Op("!").Id("ok")).Block(
			jen.Return(jen.Id(typeName).Values()),
		),
		jen.Return(jen.Id("new"+typeName).Call(
			jen.Id("t").Assert(jen.Op("*").Id("tree")),
			jen.Id("root"),
		)),
	)
}

// emitSequenceViewJen generates struct, constructor, and accessors for a sequence rule.
func emitSequenceViewJen(f *jen.File, ri RuleInfo, rules map[string]RuleInfo, exported map[string]bool) {
	viewName := viewTypeName(ri.Name, exported)
	children := sequenceNamedChildren(ri, rules)

	// --- struct definition ---
	f.Comment(viewName + " is a read-only view over a " + ri.Name + " node.")
	f.Comment("Child references are resolved once at construction time.")
	f.Type().Id(viewName).StructFunc(func(g *jen.Group) {
		g.Id("t").Op("*").Id("tree")
		g.Id("id").Id("NodeID")
		for _, nc := range children {
			if nc.repeated {
				g.Id("_" + fieldName(nc.ruleName)).Index().Id("NodeID")
			} else {
				g.Id("_" + fieldName(nc.ruleName)).Id("NodeID")
				g.Id("_has" + nc.ruleName).Bool()
			}
		}
	})

	// --- String method ---
	emitTextMethodJen(f, viewName)

	// --- constructor ---
	f.Func().Id("new"+ri.Name).Params(
		jen.Id("t").Op("*").Id("tree"),
		jen.Id("id").Id("NodeID"),
	).Id(viewName).BlockFunc(func(g *jen.Group) {
		g.Id("v").Op(":=").Add(viewLit(viewName, jen.Id("t"), jen.Id("id")))
		g.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("t").Dot("Child").Call(jen.Id("id"))
		g.If(jen.Op("!").Id("ok")).Block(jen.Return(jen.Id("v")))

		// Arena marks for repeated children
		for _, nc := range children {
			if nc.repeated {
				g.Id("mark_" + fieldName(nc.ruleName)).Op(":=").Id("t").Dot("viewMark").Call()
			}
		}

		// Sequence branch: child is NodeType_Sequence
		g.If(jen.Id("t").Dot("Type").Call(jen.Id("child")).Op("==").Id("NodeType_Sequence")).BlockFunc(func(seq *jen.Group) {
			seq.Id("cr").Op(":=").Id("t").Dot("childRanges").Index(jen.Id("t").Dot("nodes").Index(jen.Id("child")).Dot("childID"))
			seq.For(jen.Id("i").Op(":=").Id("cr").Dot("start"), jen.Id("i").Op("<").Id("cr").Dot("end"), jen.Id("i").Op("++")).BlockFunc(func(loop *jen.Group) {
				loop.Id("cid").Op(":=").Id("t").Dot("children").Index(jen.Id("i"))
				loop.If(jen.Id("t").Dot("Type").Call(jen.Id("cid")).Op("!=").Id("NodeType_Node")).Block(jen.Continue())
				loop.Switch(jen.Id("t").Dot("NameID").Call(jen.Id("cid"))).BlockFunc(func(sw *jen.Group) {
					for _, nc := range children {
						emitSequenceConstructorCaseJen(sw, nc)
					}
				})
			})
		}).Else().If(jen.Id("t").Dot("Type").Call(jen.Id("child")).Op("==").Id("NodeType_Node")).BlockFunc(func(node *jen.Group) {
			// Single-child branch
			node.Switch(jen.Id("t").Dot("NameID").Call(jen.Id("child"))).BlockFunc(func(sw *jen.Group) {
				for _, nc := range children {
					sw.Case(jen.Id("_nameID_" + nc.ruleName)).BlockFunc(func(body *jen.Group) {
						if nc.repeated {
							body.Id("t").Dot("viewAppend").Call(jen.Id("child"))
						} else {
							body.Id("v").Dot("_" + fieldName(nc.ruleName)).Op("=").Id("child")
							body.Id("v").Dot("_has" + nc.ruleName).Op("=").True()
						}
					})
				}
			})
		})

		// Assign arena slices for repeated children
		for _, nc := range children {
			if nc.repeated {
				fn := fieldName(nc.ruleName)
				g.Id("v").Dot("_" + fn).Op("=").Id("t").Dot("viewSlice").Call(jen.Id("mark_" + fn))
			}
		}

		g.Return(jen.Id("v"))
	})

	// --- accessors ---
	for _, nc := range children {
		if nc.repeated {
			emitRepeatedAccessorJen(f, viewName, nc, rules, exported)
		} else if nc.rule.Kind == RuleLeaf {
			emitLeafAccessorJen(f, viewName, nc)
		} else {
			emitSingleAccessorJen(f, viewName, nc, rules, exported)
		}
	}
}

func emitSequenceConstructorCaseJen(sw *jen.Group, nc namedChild) {
	sw.Case(jen.Id("_nameID_" + nc.ruleName)).BlockFunc(func(body *jen.Group) {
		if nc.repeated {
			body.Id("t").Dot("viewAppend").Call(jen.Id("cid"))
		} else {
			body.If(jen.Op("!").Id("v").Dot("_has"+nc.ruleName)).Block(
				jen.Id("v").Dot("_"+fieldName(nc.ruleName)).Op("=").Id("cid"),
				jen.Id("v").Dot("_has"+nc.ruleName).Op("=").True(),
			)
		}
	})
}

func emitLeafAccessorJen(f *jen.File, viewName string, nc namedChild) {
	methName := accessorName(nc.ruleName)
	f.Comment(methName + " returns the " + nc.ruleName + " text.")
	f.Func().Params(jen.Id("v").Id(viewName)).Id(methName).Params().String().Block(
		jen.If(jen.Op("!").Id("v").Dot("_has"+nc.ruleName)).Block(
			jen.Return(jen.Lit("")),
		),
		jen.Return(jen.Id("v").Dot("t").Dot("Text").Call(jen.Id("v").Dot("_"+fieldName(nc.ruleName)))),
	)
}

func emitSingleAccessorJen(f *jen.File, viewName string, nc namedChild, rules map[string]RuleInfo, exported map[string]bool) {
	childViewName := viewTypeName(nc.ruleName, exported)
	isSeq := nc.rule.Kind == RuleSequence
	methName := accessorName(nc.ruleName)

	f.Comment(methName + " returns a view over the " + nc.ruleName + " child.")
	f.Func().Params(jen.Id("v").Id(viewName)).Id(methName).Params().Params(
		jen.Id(childViewName), jen.Bool(),
	).BlockFunc(func(g *jen.Group) {
		g.If(jen.Op("!").Id("v").Dot("_has" + nc.ruleName)).Block(
			jen.Return(jen.Id(childViewName).Values(), jen.False()),
		)
		if isSeq {
			g.Return(jen.Id("new"+nc.ruleName).Call(
				jen.Id("v").Dot("t"), jen.Id("v").Dot("_"+fieldName(nc.ruleName)),
			), jen.True())
		} else {
			g.Return(viewLit(childViewName, jen.Id("v").Dot("t"), jen.Id("v").Dot("_"+fieldName(nc.ruleName))), jen.True())
		}
	})
}

func emitRepeatedAccessorJen(f *jen.File, viewName string, nc namedChild, rules map[string]RuleInfo, exported map[string]bool) {
	childViewName := viewTypeName(nc.ruleName, exported)
	isSeq := nc.rule.Kind == RuleSequence
	methName := accessorName(nc.ruleName)
	fn := fieldName(nc.ruleName)

	// Count method
	f.Comment(methName + "Count returns the number of " + nc.ruleName + " children.")
	f.Func().Params(jen.Id("v").Id(viewName)).Id(methName + "Count").Params().Int().Block(
		jen.Return(jen.Len(jen.Id("v").Dot("_" + fn))),
	)

	if nc.rule.Kind == RuleLeaf {
		// Leaf: At returns string
		f.Comment(methName + "At returns the text of the i-th " + nc.ruleName + " child.")
		f.Func().Params(jen.Id("v").Id(viewName)).Id(methName + "At").Params(
			jen.Id("i").Int(),
		).String().Block(
			jen.Return(jen.Id("v").Dot("t").Dot("Text").Call(jen.Id("v").Dot("_" + fn).Index(jen.Id("i")))),
		)
	} else {
		// Non-leaf: At returns view
		f.Comment(methName + "At returns a view over the i-th " + nc.ruleName + " child.")
		f.Func().Params(jen.Id("v").Id(viewName)).Id(methName + "At").Params(
			jen.Id("i").Int(),
		).Id(childViewName).BlockFunc(func(g *jen.Group) {
			if isSeq {
				g.Return(jen.Id("new"+nc.ruleName).Call(
					jen.Id("v").Dot("t"), jen.Id("v").Dot("_"+fn).Index(jen.Id("i")),
				))
			} else {
				g.Return(viewLit(childViewName, jen.Id("v").Dot("t"), jen.Id("v").Dot("_"+fn).Index(jen.Id("i"))))
			}
		})
	}
}

// emitChoiceViewJen generates a thin wrapper with per-choice accessor methods.
func emitChoiceViewJen(f *jen.File, ri RuleInfo, rules map[string]RuleInfo, exported map[string]bool) {
	viewName := viewTypeName(ri.Name, exported)

	emitViewStructJen(f, viewName, ri.Name)
	emitTextMethodJen(f, viewName)

	for _, choice := range ri.Choices {
		if choice == "" {
			continue
		}
		if litText, ok := IsChoiceLiteral(choice); ok {
			emitLiteralChoiceAccessorJen(f, viewName, litText)
			continue
		}
		childRule, ok := rules[choice]
		if !ok {
			continue
		}

		methName := accessorName(choice)

		if childRule.Kind == RuleLeaf {
			// Leaf choice: returns (string, bool)
			f.Comment(methName + " returns the " + choice + " text if this alternative matched.")
			f.Func().Params(jen.Id("v").Id(viewName)).Id(methName).Params().Params(
				jen.String(), jen.Bool(),
			).Block(
				jen.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("v").Dot("t").Dot("Child").Call(jen.Id("v").Dot("id")),
				jen.If(jen.Op("!").Id("ok").Op("||").Op("!").Id("v").Dot("t").Dot("IsNamed").Call(
					jen.Id("child"), jen.Id("_nameID_"+choice),
				)).Block(
					jen.Return(jen.Lit(""), jen.False()),
				),
				jen.Return(jen.Id("v").Dot("t").Dot("Text").Call(jen.Id("child")), jen.True()),
			)
		} else {
			// Non-leaf choice: returns (ViewType, bool)
			childViewName := viewTypeName(choice, exported)
			isSeq := childRule.Kind == RuleSequence

			f.Comment(methName + " returns a " + childViewName + " if this alternative matched.")
			f.Func().Params(jen.Id("v").Id(viewName)).Id(methName).Params().Params(
				jen.Id(childViewName), jen.Bool(),
			).BlockFunc(func(g *jen.Group) {
				g.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("v").Dot("t").Dot("Child").Call(jen.Id("v").Dot("id"))
				g.If(jen.Op("!").Id("ok").Op("||").Op("!").Id("v").Dot("t").Dot("IsNamed").Call(
					jen.Id("child"), jen.Id("_nameID_"+choice),
				)).Block(
					jen.Return(jen.Id(childViewName).Values(), jen.False()),
				)
				if isSeq {
					g.Return(jen.Id("new"+choice).Call(jen.Id("v").Dot("t"), jen.Id("child")), jen.True())
				} else {
					g.Return(viewLit(childViewName, jen.Id("v").Dot("t"), jen.Id("child")), jen.True())
				}
			})
		}
	}
}

func emitLiteralChoiceAccessorJen(f *jen.File, viewName string, litText string) {
	methName := "Is" + strings.ToUpper(litText[:1]) + litText[1:]
	f.Comment(methName + " reports whether this value is the literal " + `"` + litText + `"` + ".")
	f.Func().Params(jen.Id("v").Id(viewName)).Id(methName).Params().Bool().Block(
		jen.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("v").Dot("t").Dot("Child").Call(jen.Id("v").Dot("id")),
		jen.If(jen.Op("!").Id("ok").Op("||").Id("v").Dot("t").Dot("Type").Call(jen.Id("child")).Op("!=").Id("NodeType_String")).Block(
			jen.Return(jen.False()),
		),
		jen.Return(jen.Id("v").Dot("t").Dot("Text").Call(jen.Id("child")).Op("==").Lit(litText)),
	)
}

func emitRepeatViewJen(f *jen.File, ri RuleInfo, rules map[string]RuleInfo, exported map[string]bool) {
	viewName := viewTypeName(ri.Name, exported)

	emitViewStructJen(f, viewName, ri.Name)
	emitTextMethodJen(f, viewName)

	if ri.Inner == "" {
		return
	}
	innerRule, ok := rules[ri.Inner]
	if !ok {
		return
	}

	nc := namedChild{ruleName: ri.Inner, rule: innerRule, repeated: true}
	childViewName := viewTypeName(nc.ruleName, exported)
	isSeq := nc.rule.Kind == RuleSequence

	// Determine callback parameter type
	var callbackParam jen.Code
	if nc.rule.Kind == RuleLeaf {
		callbackParam = jen.String()
		f.Comment("Visit" + nc.ruleName + " calls fn for each " + nc.ruleName + " child text.")
	} else {
		callbackParam = jen.Id(childViewName)
		f.Comment("Visit" + nc.ruleName + " calls fn for each " + nc.ruleName + " child view.")
	}

	f.Func().Params(jen.Id("v").Id(viewName)).Id("Visit" + nc.ruleName).Params(
		jen.Id("fn").Func().Params(callbackParam).Bool(),
	).BlockFunc(func(g *jen.Group) {
		g.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("v").Dot("t").Dot("Child").Call(jen.Id("v").Dot("id"))
		g.If(jen.Op("!").Id("ok")).Block(jen.Return())
		g.If(jen.Id("v").Dot("t").Dot("Type").Call(jen.Id("child")).Op("!=").Id("NodeType_Sequence")).Block(jen.Return())
		g.Id("cr").Op(":=").Id("v").Dot("t").Dot("childRanges").Index(
			jen.Id("v").Dot("t").Dot("nodes").Index(jen.Id("child")).Dot("childID"),
		)
		g.For(jen.Id("i").Op(":=").Id("cr").Dot("start"), jen.Id("i").Op("<").Id("cr").Dot("end"), jen.Id("i").Op("++")).BlockFunc(func(loop *jen.Group) {
			loop.Id("cid").Op(":=").Id("v").Dot("t").Dot("children").Index(jen.Id("i"))
			loop.If(jen.Id("v").Dot("t").Dot("IsNamed").Call(
				jen.Id("cid"), jen.Id("_nameID_"+nc.ruleName),
			)).BlockFunc(func(match *jen.Group) {
				var callArg jen.Code
				if nc.rule.Kind == RuleLeaf {
					callArg = jen.Id("v").Dot("t").Dot("Text").Call(jen.Id("cid"))
				} else if isSeq {
					callArg = jen.Id("new"+nc.ruleName).Call(jen.Id("v").Dot("t"), jen.Id("cid"))
				} else {
					callArg = viewLit(childViewName, jen.Id("v").Dot("t"), jen.Id("cid"))
				}
				match.If(jen.Op("!").Id("fn").Call(callArg)).Block(jen.Return())
			})
		})
	})
}

func emitAliasViewJen(f *jen.File, ri RuleInfo, rules map[string]RuleInfo, exported map[string]bool) {
	viewName := viewTypeName(ri.Name, exported)

	emitViewStructJen(f, viewName, ri.Name)
	emitTextMethodJen(f, viewName)

	if ri.Inner == "" {
		return
	}
	innerRule, ok := rules[ri.Inner]
	if !ok || innerRule.Kind == RuleLeaf {
		return
	}

	childViewName := viewTypeName(ri.Inner, exported)
	isSeq := innerRule.Kind == RuleSequence
	methName := accessorName(ri.Inner)

	f.Comment(methName + " returns a view over the aliased " + ri.Inner + " rule.")
	f.Func().Params(jen.Id("v").Id(viewName)).Id(methName).Params().Params(
		jen.Id(childViewName), jen.Bool(),
	).BlockFunc(func(g *jen.Group) {
		g.List(jen.Id("child"), jen.Id("ok")).Op(":=").Id("v").Dot("t").Dot("Child").Call(jen.Id("v").Dot("id"))
		g.If(jen.Op("!").Id("ok")).Block(
			jen.Return(jen.Id(childViewName).Values(), jen.False()),
		)
		if isSeq {
			g.Return(jen.Id("new"+ri.Inner).Call(jen.Id("v").Dot("t"), jen.Id("child")), jen.True())
		} else {
			g.Return(viewLit(childViewName, jen.Id("v").Dot("t"), jen.Id("child")), jen.True())
		}
	})
}
