package extract

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"
)

type renderData struct {
	Package     string
	GrammarPath string
	Functions   string
}

const fileTmpl = `// Code generated by langlang extract; DO NOT EDIT.
// Grammar: {{.GrammarPath}}

package {{.Package}}

import "fmt"

var _ = fmt.Errorf

{{.Functions}}
`

// RenderFile produces a formatted Go source file containing extraction functions.
func RenderFile(
	pkg, grammarPath string,
	structs []StructInfo,
	rules map[string]RuleInfo,
) (string, error) {
	var funcs strings.Builder
	for _, si := range structs {
		funcs.WriteString(emitExtractFunction(si, rules, true))
		funcs.WriteString("\n")
	}

	tmpl, err := template.New("extract").Parse(fileTmpl)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	var buf bytes.Buffer
	err = tmpl.Execute(&buf, renderData{
		Package:     pkg,
		GrammarPath: grammarPath,
		Functions:   funcs.String(),
	})
	if err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("gofmt: %w (source:\n%s)", err, buf.String())
	}

	return string(formatted), nil
}
