package binary

import (
	"fmt"
	"go/format"
	"strings"
	"unicode"

	langlang "github.com/clarete/langlang/go"
)

// Options configures the binary codegen output.
type Options struct {
	PackageName string
	SourceFile  string
}

// ruleInfo describes a grammar rule's structure for codegen.
type ruleInfo struct {
	Name     string
	GoName   string
	Fields   []fieldInfo
	SeqItems []seqItem // all items in order, including length fields
}

// fieldInfo describes a struct field derived from a name binding.
type fieldInfo struct {
	Name   string // binding name (e.g. "data")
	GoName string // Go field name (e.g. "Data")
	GoType string // Go type (e.g. "[]byte")
}

// seqItem describes one item in the rule's sequence for decode/encode ordering.
type seqItem struct {
	BindingName   string // name from NameBindingNode (empty if unbinding)
	GoName        string // PascalCase version
	IsLengthField bool   // true if consumed by bytes() or {count}
	Kind          seqItemKind
	Width         int    // for numeric primitives
	BigEndian     bool   // for numeric primitives
	LenRef        string // for bytes consume: binding name providing the length
	CountRef      string // for counted repetition: binding name providing the count
	RuleRef       string // for counted repetition: repeated rule name
	RuleName      string // for rule reference
}

type seqItemKind int

const (
	itemNumeric seqItemKind = iota
	itemBytes
	itemCounted
	itemRuleRef
)

// Generate produces Go source code with struct types and Decode/Encode/Size
// functions from a grammar containing binary primitives.
func Generate(grammar *langlang.GrammarNode, opts Options) (string, error) {
	var buf strings.Builder

	fmt.Fprintf(&buf, "// Code generated by langlang codegen, DO NOT EDIT.\n")
	if opts.SourceFile != "" {
		fmt.Fprintf(&buf, "// Source: %s\n", opts.SourceFile)
	}
	fmt.Fprintf(&buf, "\npackage %s\n\n", opts.PackageName)
	fmt.Fprintf(&buf, "import (\n")
	fmt.Fprintf(&buf, "\t\"encoding/binary\"\n")
	fmt.Fprintf(&buf, "\t\"fmt\"\n")
	fmt.Fprintf(&buf, ")\n\n")
	// Suppress unused import warnings
	fmt.Fprintf(&buf, "var _ = binary.LittleEndian\n")
	fmt.Fprintf(&buf, "var _ = fmt.Errorf\n\n")

	for _, def := range grammar.Definitions {
		info, err := analyzeRule(def)
		if err != nil {
			return "", fmt.Errorf("rule %s: %w", def.Name, err)
		}
		if info == nil {
			continue
		}
		emitStruct(&buf, info)
		emitDecode(&buf, info)
		emitEncode(&buf, info)
		emitSize(&buf, info)
	}

	src, err := format.Source([]byte(buf.String()))
	if err != nil {
		return buf.String(), fmt.Errorf("gofmt: %w\n\nRaw output:\n%s", err, buf.String())
	}
	return string(src), nil
}

// analyzeRule extracts struct field info from a definition's expression.
// Returns nil if the rule has no name bindings (nothing to generate).
func analyzeRule(def *langlang.DefinitionNode) (*ruleInfo, error) {
	seq, ok := def.Expr.(*langlang.SequenceNode)
	if !ok {
		return nil, nil
	}

	info := &ruleInfo{
		Name:   def.Name,
		GoName: toGoName(def.Name),
	}

	// First pass: collect all bindings and identify length/count fields
	lengthFields := map[string]bool{} // binding names consumed by bytes() or {count}
	for _, item := range seq.Items {
		langlang.Inspect(item, func(n langlang.AstNode) bool {
			switch node := n.(type) {
			case *langlang.BytesConsumeNode:
				lengthFields[node.Name] = true
			case *langlang.CountedRepetitionNode:
				lengthFields[node.Count] = true
			}
			return true
		})
	}

	// Second pass: build field list and sequence items
	for _, item := range seq.Items {
		binding, ok := item.(*langlang.NameBindingNode)
		if !ok {
			continue
		}

		si, err := analyzeExpr(binding.Name, binding.Expr)
		if err != nil {
			return nil, err
		}
		si.GoName = toGoName(binding.Name)
		si.IsLengthField = lengthFields[binding.Name]
		info.SeqItems = append(info.SeqItems, si)

		if si.IsLengthField {
			continue
		}

		goType := goTypeForItem(si)
		info.Fields = append(info.Fields, fieldInfo{
			Name:   binding.Name,
			GoName: si.GoName,
			GoType: goType,
		})
	}

	if len(info.Fields) == 0 {
		return nil, nil
	}
	return info, nil
}

func analyzeExpr(bindingName string, expr langlang.AstNode) (seqItem, error) {
	switch node := expr.(type) {
	case *langlang.NumericPrimitiveNode:
		return seqItem{
			BindingName: bindingName,
			Kind:        itemNumeric,
			Width:       node.Width,
			BigEndian:   node.BigEndian,
		}, nil
	case *langlang.BytesConsumeNode:
		return seqItem{
			BindingName: bindingName,
			Kind:        itemBytes,
			LenRef:      node.Name,
		}, nil
	case *langlang.CountedRepetitionNode:
		ruleName := ""
		if ident, ok := node.Expr.(*langlang.IdentifierNode); ok {
			ruleName = ident.Value
		}
		return seqItem{
			BindingName: bindingName,
			Kind:        itemCounted,
			CountRef:    node.Count,
			RuleRef:     ruleName,
		}, nil
	case *langlang.IdentifierNode:
		return seqItem{
			BindingName: bindingName,
			Kind:        itemRuleRef,
			RuleName:    node.Value,
		}, nil
	default:
		return seqItem{}, fmt.Errorf("unsupported expression type %T for binding %q", expr, bindingName)
	}
}

func goTypeForItem(si seqItem) string {
	switch si.Kind {
	case itemNumeric:
		return goNumericType(si.Width)
	case itemBytes:
		return "[]byte"
	case itemCounted:
		return "[]" + toGoName(si.RuleRef)
	case itemRuleRef:
		return toGoName(si.RuleName)
	default:
		return "any"
	}
}

func goNumericType(width int) string {
	switch width {
	case 1:
		return "uint8"
	case 2:
		return "uint16"
	case 4:
		return "uint32"
	case 8:
		return "uint64"
	default:
		return "uint32"
	}
}

func emitStruct(buf *strings.Builder, info *ruleInfo) {
	fmt.Fprintf(buf, "type %s struct {\n", info.GoName)
	for _, f := range info.Fields {
		fmt.Fprintf(buf, "\t%s %s\n", f.GoName, f.GoType)
	}
	fmt.Fprintf(buf, "}\n\n")
}

// varName returns a safe local variable name for a binding.
// Length/count fields get a v_ prefix to avoid shadowing; struct fields
// are assigned directly to out.GoName.
func varName(si seqItem) string {
	if si.IsLengthField {
		return "v_" + si.BindingName
	}
	return "out." + si.GoName
}

// lenVarName returns the local variable name for a referenced length/count binding.
func lenVarName(name string) string {
	return "v_" + name
}

func emitDecode(buf *strings.Builder, info *ruleInfo) {
	fmt.Fprintf(buf, "func Decode%s(data []byte) (%s, int, error) {\n", info.GoName, info.GoName)
	fmt.Fprintf(buf, "\tvar out %s\n", info.GoName)
	fmt.Fprintf(buf, "\toff := 0\n")

	for _, si := range info.SeqItems {
		vn := varName(si)
		switch si.Kind {
		case itemNumeric:
			fmt.Fprintf(buf, "\tif len(data) < off+%d {\n", si.Width)
			fmt.Fprintf(buf, "\t\treturn out, 0, fmt.Errorf(\"Decode%s: need %%d bytes for %s at offset %%d, have %%d\", %d, off, len(data))\n",
				info.GoName, si.BindingName, si.Width)
			fmt.Fprintf(buf, "\t}\n")
			if si.IsLengthField {
				fmt.Fprintf(buf, "\t%s := %s(%s)\n", vn, goNumericType(si.Width), decodeNumeric(si.Width, si.BigEndian))
			} else {
				fmt.Fprintf(buf, "\t%s = %s\n", vn, decodeNumeric(si.Width, si.BigEndian))
			}
			fmt.Fprintf(buf, "\toff += %d\n", si.Width)

		case itemBytes:
			lvn := lenVarName(si.LenRef)
			fmt.Fprintf(buf, "\tif len(data) < off+int(%s) {\n", lvn)
			fmt.Fprintf(buf, "\t\treturn out, 0, fmt.Errorf(\"Decode%s: need %%d bytes for %s at offset %%d, have %%d\", %s, off, len(data))\n",
				info.GoName, si.BindingName, lvn)
			fmt.Fprintf(buf, "\t}\n")
			fmt.Fprintf(buf, "\t%s = make([]byte, %s)\n", vn, lvn)
			fmt.Fprintf(buf, "\tcopy(%s, data[off:off+int(%s)])\n", vn, lvn)
			fmt.Fprintf(buf, "\toff += int(%s)\n", lvn)

		case itemCounted:
			cvn := lenVarName(si.CountRef)
			fmt.Fprintf(buf, "\t%s = make([]%s, %s)\n", vn, toGoName(si.RuleRef), cvn)
			fmt.Fprintf(buf, "\tfor i := 0; i < int(%s); i++ {\n", cvn)
			fmt.Fprintf(buf, "\t\titem, n, err := Decode%s(data[off:])\n", toGoName(si.RuleRef))
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn out, 0, fmt.Errorf(\"Decode%s: %s[%%d]: %%w\", i, err)\n", info.GoName, si.BindingName)
			fmt.Fprintf(buf, "\t\t}\n")
			fmt.Fprintf(buf, "\t\t%s[i] = item\n", vn)
			fmt.Fprintf(buf, "\t\toff += n\n")
			fmt.Fprintf(buf, "\t}\n")

		case itemRuleRef:
			fmt.Fprintf(buf, "\t{\n")
			fmt.Fprintf(buf, "\t\tval, n, err := Decode%s(data[off:])\n", toGoName(si.RuleName))
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn out, 0, fmt.Errorf(\"Decode%s: %s: %%w\", err)\n", info.GoName, si.BindingName)
			fmt.Fprintf(buf, "\t\t}\n")
			fmt.Fprintf(buf, "\t\t%s = val\n", vn)
			fmt.Fprintf(buf, "\t\toff += n\n")
			fmt.Fprintf(buf, "\t}\n")
		}
	}

	fmt.Fprintf(buf, "\treturn out, off, nil\n")
	fmt.Fprintf(buf, "}\n\n")
}

func emitEncode(buf *strings.Builder, info *ruleInfo) {
	fmt.Fprintf(buf, "func Encode%s(v *%s) ([]byte, error) {\n", info.GoName, info.GoName)
	fmt.Fprintf(buf, "\tsize := Size%s(v)\n", info.GoName)
	fmt.Fprintf(buf, "\tbuf := make([]byte, size)\n")
	fmt.Fprintf(buf, "\toff := 0\n")

	for _, si := range info.SeqItems {
		switch si.Kind {
		case itemNumeric:
			computedValue := computeEncoderValue(si, info)
			encodeNumeric(buf, si.Width, si.BigEndian, computedValue)
			fmt.Fprintf(buf, "\toff += %d\n", si.Width)

		case itemBytes:
			fmt.Fprintf(buf, "\tcopy(buf[off:], v.%s)\n", si.GoName)
			fmt.Fprintf(buf, "\toff += len(v.%s)\n", si.GoName)

		case itemCounted:
			fmt.Fprintf(buf, "\tfor i := range v.%s {\n", si.GoName)
			fmt.Fprintf(buf, "\t\tenc, err := Encode%s(&v.%s[i])\n", toGoName(si.RuleRef), si.GoName)
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"Encode%s: %s[%%d]: %%w\", i, err)\n", info.GoName, si.BindingName)
			fmt.Fprintf(buf, "\t\t}\n")
			fmt.Fprintf(buf, "\t\tcopy(buf[off:], enc)\n")
			fmt.Fprintf(buf, "\t\toff += len(enc)\n")
			fmt.Fprintf(buf, "\t}\n")

		case itemRuleRef:
			fmt.Fprintf(buf, "\t{\n")
			fmt.Fprintf(buf, "\t\tenc, err := Encode%s(&v.%s)\n", toGoName(si.RuleName), si.GoName)
			fmt.Fprintf(buf, "\t\tif err != nil {\n")
			fmt.Fprintf(buf, "\t\t\treturn nil, fmt.Errorf(\"Encode%s: %s: %%w\", err)\n", info.GoName, si.BindingName)
			fmt.Fprintf(buf, "\t\t}\n")
			fmt.Fprintf(buf, "\t\tcopy(buf[off:], enc)\n")
			fmt.Fprintf(buf, "\t\toff += len(enc)\n")
			fmt.Fprintf(buf, "\t}\n")
		}
	}

	fmt.Fprintf(buf, "\treturn buf, nil\n")
	fmt.Fprintf(buf, "}\n\n")
}

func emitSize(buf *strings.Builder, info *ruleInfo) {
	fmt.Fprintf(buf, "func Size%s(v *%s) int {\n", info.GoName, info.GoName)
	fmt.Fprintf(buf, "\tsize := 0\n")

	for _, si := range info.SeqItems {
		switch si.Kind {
		case itemNumeric:
			fmt.Fprintf(buf, "\tsize += %d\n", si.Width)
		case itemBytes:
			fmt.Fprintf(buf, "\tsize += len(v.%s)\n", si.GoName)
		case itemCounted:
			fmt.Fprintf(buf, "\tfor i := range v.%s {\n", si.GoName)
			fmt.Fprintf(buf, "\t\tsize += Size%s(&v.%s[i])\n", toGoName(si.RuleRef), si.GoName)
			fmt.Fprintf(buf, "\t}\n")
		case itemRuleRef:
			fmt.Fprintf(buf, "\tsize += Size%s(&v.%s)\n", toGoName(si.RuleName), si.GoName)
		}
	}

	fmt.Fprintf(buf, "\treturn size\n")
	fmt.Fprintf(buf, "}\n\n")
}

// computeEncoderValue returns the Go expression for the encoder value of a
// numeric field. For length fields (consumed by bytes()), it computes from
// the data. For count fields (consumed by {count}), it computes from the slice.
// Otherwise it reads from the struct field.
func computeEncoderValue(si seqItem, info *ruleInfo) string {
	for _, other := range info.SeqItems {
		if other.Kind == itemBytes && other.LenRef == si.BindingName {
			return fmt.Sprintf("uint32(len(v.%s))", other.GoName)
		}
		if other.Kind == itemCounted && other.CountRef == si.BindingName {
			return fmt.Sprintf("uint32(len(v.%s))", other.GoName)
		}
	}
	return fmt.Sprintf("v.%s", si.GoName)
}

func decodeNumeric(width int, bigEndian bool) string {
	if width == 1 {
		return "data[off]"
	}
	order := "LittleEndian"
	if bigEndian {
		order = "BigEndian"
	}
	switch width {
	case 2:
		return fmt.Sprintf("binary.%s.Uint16(data[off:])", order)
	case 4:
		return fmt.Sprintf("binary.%s.Uint32(data[off:])", order)
	case 8:
		return fmt.Sprintf("binary.%s.Uint64(data[off:])", order)
	default:
		return "0"
	}
}

func encodeNumeric(buf *strings.Builder, width int, bigEndian bool, value string) {
	if width == 1 {
		fmt.Fprintf(buf, "\tbuf[off] = byte(%s)\n", value)
		return
	}
	order := "LittleEndian"
	if bigEndian {
		order = "BigEndian"
	}
	switch width {
	case 2:
		fmt.Fprintf(buf, "\tbinary.%s.PutUint16(buf[off:], uint16(%s))\n", order, value)
	case 4:
		fmt.Fprintf(buf, "\tbinary.%s.PutUint32(buf[off:], uint32(%s))\n", order, value)
	case 8:
		fmt.Fprintf(buf, "\tbinary.%s.PutUint64(buf[off:], uint64(%s))\n", order, value)
	}
}

// toGoName converts a snake_case name to PascalCase.
func toGoName(name string) string {
	parts := strings.Split(name, "_")
	var result strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		runes := []rune(part)
		runes[0] = unicode.ToUpper(runes[0])
		result.WriteString(string(runes))
	}
	return result.String()
}
