// Code generated by langlang extract -arena (jen); DO NOT EDIT.
// Grammar: ../docs/live/assets/examples/json/json.peg

package jsonextract

import "fmt"

const (
	_arenaNameID_Object int32 = 20
	_arenaNameID_Array  int32 = 21
	_arenaNameID_String int32 = 22
	_arenaNameID_Number int32 = 28
	_arenaNameID_Member int32 = 32
	_arenaNameID_Value  int32 = 18
)

type JsonextractArenas struct {
	JSONValues           []JSONValue
	JSONObjects          []JSONObject
	JSONMembers          []JSONMember
	JSONArrays           []JSONArray
	JSONObjectMembersBuf []JSONMember
	JSONArrayItemsBuf    []JSONValue
	StringBuf            []string
}
type JsonextractNodeCounts struct {
	JSONValues  int
	JSONObjects int
	JSONMembers int
	JSONArrays  int
	Strings     int
}

func (a *JsonextractArenas) Alloc(c JsonextractNodeCounts) {
	a.JSONValues = make([]JSONValue, 0, c.JSONValues)
	a.JSONObjects = make([]JSONObject, 0, c.JSONObjects)
	a.JSONMembers = make([]JSONMember, 0, c.JSONMembers)
	a.JSONArrays = make([]JSONArray, 0, c.JSONArrays)
	a.JSONObjectMembersBuf = make([]JSONMember, 0, c.JSONMembers)
	a.JSONArrayItemsBuf = make([]JSONValue, 0, c.JSONValues)
	a.StringBuf = make([]string, 0, c.Strings)
}
func (a *JsonextractArenas) Reset() {
	a.JSONValues = a.JSONValues[:0]
	a.JSONObjects = a.JSONObjects[:0]
	a.JSONMembers = a.JSONMembers[:0]
	a.JSONArrays = a.JSONArrays[:0]
	a.JSONObjectMembersBuf = a.JSONObjectMembersBuf[:0]
	a.JSONArrayItemsBuf = a.JSONArrayItemsBuf[:0]
	a.StringBuf = a.StringBuf[:0]
}
func (a *JsonextractArenas) allocString(s string) *string {
	idx := len(a.StringBuf)
	a.StringBuf = append(a.StringBuf, s)
	return &a.StringBuf[idx]
}
func ExtractJSONValueArena(t *tree, id NodeID, a *JsonextractArenas) (*JSONValue, error) {
	idx := len(a.JSONValues)
	a.JSONValues = append(a.JSONValues, JSONValue{})
	child, ok := t.Child(id)
	if !ok {
		return &a.JSONValues[idx], fmt.Errorf("JSONValue: no child")
	}
	switch {
	case t.IsNamed(child, _arenaNameID_Object):
		val, err := ExtractJSONObjectArena(t, child, a)
		if err != nil {
			return &a.JSONValues[idx], err
		}
		a.JSONValues[idx].Object = val
	case t.IsNamed(child, _arenaNameID_Array):
		val, err := ExtractJSONArrayArena(t, child, a)
		if err != nil {
			return &a.JSONValues[idx], err
		}
		a.JSONValues[idx].Array = val
	case t.IsNamed(child, _arenaNameID_String):
		a.JSONValues[idx].String = a.allocString(t.Text(child))
	case t.IsNamed(child, _arenaNameID_Number):
		a.JSONValues[idx].Number = a.allocString(t.Text(child))
	case t.Type(child) == NodeType_String:
		// literal alternative
	}
	return &a.JSONValues[idx], nil
}
func ExtractJSONObjectArena(t *tree, id NodeID, a *JsonextractArenas) (*JSONObject, error) {
	idx := len(a.JSONObjects)
	a.JSONObjects = append(a.JSONObjects, JSONObject{})
	var countMembers int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Member {
			countMembers++
			return false
		}
		return true
	})
	startMembers := len(a.JSONObjectMembersBuf)
	a.JSONObjectMembersBuf = append(a.JSONObjectMembersBuf, make([]JSONMember, countMembers)...)
	sliceMembers := a.JSONObjectMembersBuf[startMembers : startMembers+countMembers]
	var iMembers int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Member {
			val, err := ExtractJSONMemberArena(t, cid, a)
			if err == nil {
				sliceMembers[iMembers] = *val
				iMembers++
			}
			return false
		}
		return true
	})
	a.JSONObjects[idx].Members = sliceMembers[:iMembers]
	return &a.JSONObjects[idx], nil
}
func ExtractJSONMemberArena(t *tree, id NodeID, a *JsonextractArenas) (*JSONMember, error) {
	idx := len(a.JSONMembers)
	a.JSONMembers = append(a.JSONMembers, JSONMember{})
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _arenaNameID_String:
			a.JSONMembers[idx].Key = t.Text(cid)
			return false
		case _arenaNameID_Value:
			val, err := ExtractJSONValueArena(t, cid, a)
			if err == nil {
				a.JSONMembers[idx].Value = *val
			}
			return false
		}
		return true
	})
	return &a.JSONMembers[idx], nil
}
func ExtractJSONArrayArena(t *tree, id NodeID, a *JsonextractArenas) (*JSONArray, error) {
	idx := len(a.JSONArrays)
	a.JSONArrays = append(a.JSONArrays, JSONArray{})
	var countItems int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Value {
			countItems++
			return false
		}
		return true
	})
	startItems := len(a.JSONArrayItemsBuf)
	a.JSONArrayItemsBuf = append(a.JSONArrayItemsBuf, make([]JSONValue, countItems)...)
	sliceItems := a.JSONArrayItemsBuf[startItems : startItems+countItems]
	var iItems int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Value {
			val, err := ExtractJSONValueArena(t, cid, a)
			if err == nil {
				sliceItems[iItems] = *val
				iItems++
			}
			return false
		}
		return true
	})
	a.JSONArrays[idx].Items = sliceItems[:iItems]
	return &a.JSONArrays[idx], nil
}
