// Code generated by langlang extract -arena (jen); DO NOT EDIT.
// Grammar: examples/toml-extract/toml.peg

package tomlextract

import (
	"fmt"
	junction "github.com/clarete/langlang/go/junction"
)

const (
	_arenaNameID_Expression   int32 = 6
	_arenaNameID_Table        int32 = 7
	_arenaNameID_KeyVal       int32 = 16
	_arenaNameID_Key          int32 = 9
	_arenaNameID_Val          int32 = 17
	_arenaNameID_SimpleKey    int32 = 10
	_arenaNameID_BareKey      int32 = 15
	_arenaNameID_BasicString  int32 = 12
	_arenaNameID_InlineTable  int32 = 19
	_arenaNameID_Array        int32 = 20
	_arenaNameID_Number       int32 = 22
	_arenaNameID_Boolean      int32 = 23
	_arenaNameID_DateTime     int32 = 21
	_arenaNameID_InlineKeyVal int32 = 26
)

type TomlextractArenas struct {
	TOMLDocs                  []TOMLDoc
	TOMLExpressions           []TOMLExpression
	TOMLTables                []TOMLTable
	TOMLKeyVals               []TOMLKeyVal
	TOMLKeys                  []TOMLKey
	TOMLSimpleKeys            []TOMLSimpleKey
	TOMLVals                  []TOMLVal
	TOMLArrays                []TOMLArray
	TOMLInlineTables          []TOMLInlineTable
	TOMLInlineKeyVals         []TOMLInlineKeyVal
	TOMLDocExpressionsBuf     []TOMLExpression
	TOMLTableKeyValsBuf       []TOMLKeyVal
	TOMLKeySimpleKeysBuf      []TOMLSimpleKey
	TOMLArrayItemsBuf         []TOMLVal
	TOMLInlineTableKeyValsBuf []TOMLInlineKeyVal
	StringBuf                 []string
}
type TomlextractNodeCounts struct {
	TOMLDocs          int
	TOMLExpressions   int
	TOMLTables        int
	TOMLKeyVals       int
	TOMLKeys          int
	TOMLSimpleKeys    int
	TOMLVals          int
	TOMLArrays        int
	TOMLInlineTables  int
	TOMLInlineKeyVals int
	Strings           int
}

var TomlextractArenaScanSpec = junction.ScannerSpec{
	Junctions: []junction.JunctionByte{{
		Byte: '[',
		Kind: junction.JunctionOpen,
	}, {
		Byte: ']',
		Kind: junction.JunctionClose,
	}, {
		Byte: '{',
		Kind: junction.JunctionOpen,
	}, {
		Byte: '}',
		Kind: junction.JunctionClose,
	}, {
		Byte: '=',
		Kind: junction.JunctionSeparator,
	}, {
		Byte: '.',
		Kind: junction.JunctionSeparator,
	}, {
		Byte: ',',
		Kind: junction.JunctionSeparator,
	}},
	Quoting: []junction.QuotingContext{{
		Delimiter:    '"',
		EscapePrefix: '\\',
	}},
	Sequences: []junction.JunctionSequence{},
}

func EstimateTomlextractNodeCounts(hc junction.HitCounts) TomlextractNodeCounts {
	var c TomlextractNodeCounts
	// Upper-bound estimates for child slices and string pointers.
	totalSeps := hc.Seps
	totalOpens := hc.Opens
	c.TOMLDocs = totalSeps + totalOpens
	c.TOMLExpressions = totalSeps + totalOpens
	c.TOMLTables = totalSeps + totalOpens
	c.TOMLKeyVals = totalSeps + totalOpens
	c.TOMLKeys = totalSeps + totalOpens
	c.TOMLSimpleKeys = totalSeps + totalOpens
	c.TOMLVals = totalSeps + totalOpens
	c.TOMLArrays = totalSeps + totalOpens
	c.TOMLInlineTables = totalSeps + totalOpens
	c.TOMLInlineKeyVals = totalSeps + totalOpens
	c.Strings = totalSeps + totalOpens + 1
	return c
}
func (a *TomlextractArenas) Alloc(c TomlextractNodeCounts) {
	a.TOMLDocs = make([]TOMLDoc, 0, c.TOMLDocs)
	a.TOMLExpressions = make([]TOMLExpression, 0, c.TOMLExpressions)
	a.TOMLTables = make([]TOMLTable, 0, c.TOMLTables)
	a.TOMLKeyVals = make([]TOMLKeyVal, 0, c.TOMLKeyVals)
	a.TOMLKeys = make([]TOMLKey, 0, c.TOMLKeys)
	a.TOMLSimpleKeys = make([]TOMLSimpleKey, 0, c.TOMLSimpleKeys)
	a.TOMLVals = make([]TOMLVal, 0, c.TOMLVals)
	a.TOMLArrays = make([]TOMLArray, 0, c.TOMLArrays)
	a.TOMLInlineTables = make([]TOMLInlineTable, 0, c.TOMLInlineTables)
	a.TOMLInlineKeyVals = make([]TOMLInlineKeyVal, 0, c.TOMLInlineKeyVals)
	a.TOMLDocExpressionsBuf = make([]TOMLExpression, 0, c.TOMLExpressions)
	a.TOMLTableKeyValsBuf = make([]TOMLKeyVal, 0, c.TOMLKeyVals)
	a.TOMLKeySimpleKeysBuf = make([]TOMLSimpleKey, 0, c.TOMLSimpleKeys)
	a.TOMLArrayItemsBuf = make([]TOMLVal, 0, c.TOMLVals)
	a.TOMLInlineTableKeyValsBuf = make([]TOMLInlineKeyVal, 0, c.TOMLInlineKeyVals)
	a.StringBuf = make([]string, 0, c.Strings)
}
func (a *TomlextractArenas) Reset() {
	a.TOMLDocs = a.TOMLDocs[:0]
	a.TOMLExpressions = a.TOMLExpressions[:0]
	a.TOMLTables = a.TOMLTables[:0]
	a.TOMLKeyVals = a.TOMLKeyVals[:0]
	a.TOMLKeys = a.TOMLKeys[:0]
	a.TOMLSimpleKeys = a.TOMLSimpleKeys[:0]
	a.TOMLVals = a.TOMLVals[:0]
	a.TOMLArrays = a.TOMLArrays[:0]
	a.TOMLInlineTables = a.TOMLInlineTables[:0]
	a.TOMLInlineKeyVals = a.TOMLInlineKeyVals[:0]
	a.TOMLDocExpressionsBuf = a.TOMLDocExpressionsBuf[:0]
	a.TOMLTableKeyValsBuf = a.TOMLTableKeyValsBuf[:0]
	a.TOMLKeySimpleKeysBuf = a.TOMLKeySimpleKeysBuf[:0]
	a.TOMLArrayItemsBuf = a.TOMLArrayItemsBuf[:0]
	a.TOMLInlineTableKeyValsBuf = a.TOMLInlineTableKeyValsBuf[:0]
	a.StringBuf = a.StringBuf[:0]
}
func (a *TomlextractArenas) allocString(s string) *string {
	idx := len(a.StringBuf)
	a.StringBuf = append(a.StringBuf, s)
	return &a.StringBuf[idx]
}
func ExtractTOMLDocArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLDoc, error) {
	idx := len(a.TOMLDocs)
	a.TOMLDocs = append(a.TOMLDocs, TOMLDoc{})
	var countExpressions int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Expression {
			countExpressions++
			return false
		}
		return true
	})
	startExpressions := len(a.TOMLDocExpressionsBuf)
	a.TOMLDocExpressionsBuf = append(a.TOMLDocExpressionsBuf, make([]TOMLExpression, countExpressions)...)
	sliceExpressions := a.TOMLDocExpressionsBuf[startExpressions : startExpressions+countExpressions]
	var iExpressions int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Expression {
			val, err := ExtractTOMLExpressionArena(t, cid, a)
			if err == nil {
				sliceExpressions[iExpressions] = *val
				iExpressions++
			}
			return false
		}
		return true
	})
	a.TOMLDocs[idx].Expressions = sliceExpressions[:iExpressions]
	return &a.TOMLDocs[idx], nil
}
func ExtractTOMLExpressionArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLExpression, error) {
	idx := len(a.TOMLExpressions)
	a.TOMLExpressions = append(a.TOMLExpressions, TOMLExpression{})
	child, ok := t.Child(id)
	if !ok {
		return &a.TOMLExpressions[idx], fmt.Errorf("TOMLExpression: no child")
	}
	switch {
	case t.IsNamed(child, _arenaNameID_Table):
		val, err := ExtractTOMLTableArena(t, child, a)
		if err != nil {
			return &a.TOMLExpressions[idx], err
		}
		a.TOMLExpressions[idx].Table = val
	case t.IsNamed(child, _arenaNameID_KeyVal):
		val, err := ExtractTOMLKeyValArena(t, child, a)
		if err != nil {
			return &a.TOMLExpressions[idx], err
		}
		a.TOMLExpressions[idx].KeyVal = val
	case t.Type(child) == NodeType_String:
		// literal alternative
	}
	return &a.TOMLExpressions[idx], nil
}
func ExtractTOMLTableArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLTable, error) {
	idx := len(a.TOMLTables)
	a.TOMLTables = append(a.TOMLTables, TOMLTable{})
	var countKeyVals int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_KeyVal {
			countKeyVals++
			return false
		}
		return true
	})
	startKeyVals := len(a.TOMLTableKeyValsBuf)
	a.TOMLTableKeyValsBuf = append(a.TOMLTableKeyValsBuf, make([]TOMLKeyVal, countKeyVals)...)
	sliceKeyVals := a.TOMLTableKeyValsBuf[startKeyVals : startKeyVals+countKeyVals]
	var iKeyVals int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_KeyVal {
			val, err := ExtractTOMLKeyValArena(t, cid, a)
			if err == nil {
				sliceKeyVals[iKeyVals] = *val
				iKeyVals++
			}
			return false
		}
		return true
	})
	a.TOMLTables[idx].KeyVals = sliceKeyVals[:iKeyVals]
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _arenaNameID_Key:
			val, err := ExtractTOMLKeyArena(t, cid, a)
			if err == nil {
				a.TOMLTables[idx].Key = *val
			}
			return false
		}
		return true
	})
	return &a.TOMLTables[idx], nil
}
func ExtractTOMLKeyValArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLKeyVal, error) {
	idx := len(a.TOMLKeyVals)
	a.TOMLKeyVals = append(a.TOMLKeyVals, TOMLKeyVal{})
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _arenaNameID_Key:
			val, err := ExtractTOMLKeyArena(t, cid, a)
			if err == nil {
				a.TOMLKeyVals[idx].Key = *val
			}
			return false
		case _arenaNameID_Val:
			val, err := ExtractTOMLValArena(t, cid, a)
			if err == nil {
				a.TOMLKeyVals[idx].Val = *val
			}
			return false
		}
		return true
	})
	return &a.TOMLKeyVals[idx], nil
}
func ExtractTOMLKeyArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLKey, error) {
	idx := len(a.TOMLKeys)
	a.TOMLKeys = append(a.TOMLKeys, TOMLKey{})
	var countSimpleKeys int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_SimpleKey {
			countSimpleKeys++
			return false
		}
		return true
	})
	startSimpleKeys := len(a.TOMLKeySimpleKeysBuf)
	a.TOMLKeySimpleKeysBuf = append(a.TOMLKeySimpleKeysBuf, make([]TOMLSimpleKey, countSimpleKeys)...)
	sliceSimpleKeys := a.TOMLKeySimpleKeysBuf[startSimpleKeys : startSimpleKeys+countSimpleKeys]
	var iSimpleKeys int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_SimpleKey {
			val, err := ExtractTOMLSimpleKeyArena(t, cid, a)
			if err == nil {
				sliceSimpleKeys[iSimpleKeys] = *val
				iSimpleKeys++
			}
			return false
		}
		return true
	})
	a.TOMLKeys[idx].SimpleKeys = sliceSimpleKeys[:iSimpleKeys]
	return &a.TOMLKeys[idx], nil
}
func ExtractTOMLSimpleKeyArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLSimpleKey, error) {
	idx := len(a.TOMLSimpleKeys)
	a.TOMLSimpleKeys = append(a.TOMLSimpleKeys, TOMLSimpleKey{})
	child, ok := t.Child(id)
	if !ok {
		return &a.TOMLSimpleKeys[idx], fmt.Errorf("TOMLSimpleKey: no child")
	}
	switch {
	case t.IsNamed(child, _arenaNameID_BareKey):
		a.TOMLSimpleKeys[idx].BareKey = a.allocString(t.Text(child))
	case t.IsNamed(child, _arenaNameID_BasicString):
		a.TOMLSimpleKeys[idx].QuotedKey = a.allocString(t.Text(child))
	case t.Type(child) == NodeType_String:
		// literal alternative
	}
	return &a.TOMLSimpleKeys[idx], nil
}
func ExtractTOMLValArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLVal, error) {
	idx := len(a.TOMLVals)
	a.TOMLVals = append(a.TOMLVals, TOMLVal{})
	child, ok := t.Child(id)
	if !ok {
		return &a.TOMLVals[idx], fmt.Errorf("TOMLVal: no child")
	}
	switch {
	case t.IsNamed(child, _arenaNameID_InlineTable):
		val, err := ExtractTOMLInlineTableArena(t, child, a)
		if err != nil {
			return &a.TOMLVals[idx], err
		}
		a.TOMLVals[idx].InlineTable = val
	case t.IsNamed(child, _arenaNameID_Array):
		val, err := ExtractTOMLArrayArena(t, child, a)
		if err != nil {
			return &a.TOMLVals[idx], err
		}
		a.TOMLVals[idx].Array = val
	case t.IsNamed(child, _arenaNameID_BasicString):
		a.TOMLVals[idx].String = a.allocString(t.Text(child))
	case t.IsNamed(child, _arenaNameID_Number):
		a.TOMLVals[idx].Number = a.allocString(t.Text(child))
	case t.IsNamed(child, _arenaNameID_Boolean):
		a.TOMLVals[idx].Boolean = a.allocString(t.Text(child))
	case t.IsNamed(child, _arenaNameID_DateTime):
		a.TOMLVals[idx].DateTime = a.allocString(t.Text(child))
	case t.Type(child) == NodeType_String:
		// literal alternative
	}
	return &a.TOMLVals[idx], nil
}
func ExtractTOMLArrayArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLArray, error) {
	idx := len(a.TOMLArrays)
	a.TOMLArrays = append(a.TOMLArrays, TOMLArray{})
	var countItems int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Val {
			countItems++
			return false
		}
		return true
	})
	startItems := len(a.TOMLArrayItemsBuf)
	a.TOMLArrayItemsBuf = append(a.TOMLArrayItemsBuf, make([]TOMLVal, countItems)...)
	sliceItems := a.TOMLArrayItemsBuf[startItems : startItems+countItems]
	var iItems int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_Val {
			val, err := ExtractTOMLValArena(t, cid, a)
			if err == nil {
				sliceItems[iItems] = *val
				iItems++
			}
			return false
		}
		return true
	})
	a.TOMLArrays[idx].Items = sliceItems[:iItems]
	return &a.TOMLArrays[idx], nil
}
func ExtractTOMLInlineTableArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLInlineTable, error) {
	idx := len(a.TOMLInlineTables)
	a.TOMLInlineTables = append(a.TOMLInlineTables, TOMLInlineTable{})
	var countKeyVals int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_InlineKeyVal {
			countKeyVals++
			return false
		}
		return true
	})
	startKeyVals := len(a.TOMLInlineTableKeyValsBuf)
	a.TOMLInlineTableKeyValsBuf = append(a.TOMLInlineTableKeyValsBuf, make([]TOMLInlineKeyVal, countKeyVals)...)
	sliceKeyVals := a.TOMLInlineTableKeyValsBuf[startKeyVals : startKeyVals+countKeyVals]
	var iKeyVals int
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		if t.NameID(cid) == _arenaNameID_InlineKeyVal {
			val, err := ExtractTOMLInlineKeyValArena(t, cid, a)
			if err == nil {
				sliceKeyVals[iKeyVals] = *val
				iKeyVals++
			}
			return false
		}
		return true
	})
	a.TOMLInlineTables[idx].KeyVals = sliceKeyVals[:iKeyVals]
	return &a.TOMLInlineTables[idx], nil
}
func ExtractTOMLInlineKeyValArena(t *tree, id NodeID, a *TomlextractArenas) (*TOMLInlineKeyVal, error) {
	idx := len(a.TOMLInlineKeyVals)
	a.TOMLInlineKeyVals = append(a.TOMLInlineKeyVals, TOMLInlineKeyVal{})
	t.Visit(id, func(cid NodeID) bool {
		if cid == id {
			return true
		}
		if t.Type(cid) != NodeType_Node {
			return true
		}
		switch t.NameID(cid) {
		case _arenaNameID_Key:
			val, err := ExtractTOMLKeyArena(t, cid, a)
			if err == nil {
				a.TOMLInlineKeyVals[idx].Key = *val
			}
			return false
		case _arenaNameID_Val:
			val, err := ExtractTOMLValArena(t, cid, a)
			if err == nil {
				a.TOMLInlineKeyVals[idx].Val = *val
			}
			return false
		}
		return true
	})
	return &a.TOMLInlineKeyVals[idx], nil
}
